{{- if .Values.property.auth.enabled }}
{{- if not .Values.global.isViper }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "gen.admin-secret" . | nindent 2 }}
{{- end }}
{{- end }}
