apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- include "kafka.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: broker
      targetPort: 9092
    - port: 9093
      name: controller
      targetPort: 9093
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
