apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
