{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "darkice.fullname" . }}
  labels:
    {{- include "darkice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "darkice.selectorLabels" . | nindent 4 }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "darkice.fullname" . }}-np
  labels:
    {{- include "darkice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.npPort }}
  selector:
    {{- include "darkice.selectorLabels" . | nindent 4 }}
{{- end }}


