{
 "title": "vGPU",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pod Container GPU Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_gpu_memory_total",
     "legendFormat": "container_gpu_memory_total-{{pod_name}}/{{container_name}}-{{gpu_memory}}-{{node}}"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_GPU_TEMP, \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-{{gpu}}"
    }
   ]
  },
  {
   "title": "Pod Container GPU Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_gpu_utilization",
     "legendFormat": "container_gpu_utilization-{{pod_name}}/{{container_name}}-{{gpu}}-{{node}}"
    }
   ]
  },
  {
   "title": "Pod Request Mem",
   "type": "graph",
   "description": "Unit(256M)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"sensetime_com_vcuda_memory\"}",
     "legendFormat": "{{pod}}/{{container}}-{{node}}"
    }
   ]
  },
  {
   "title": "Node GPU Mem Used",
   "type": "graph",
   "description": "DCGM_FI_DEV_FB_USED",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "MiB" }
   ],
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_FB_USED, \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-{{gpu}}"
    }
   ]
  },
  {
   "title": "Node vGPU Mem Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable{resource=\"sensetime_com_vcuda_memory\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node GPU Util Used",
   "type": "graph",
   "description": "DCGM_FI_DEV_GPU_UTIL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_GPU_UTIL, \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-{{gpu}}"
    }
   ]
  },
  {
   "title": "Container Request Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"sensetime_com_vcuda_core\"}",
     "legendFormat": "{{pod}}/{{container}}-{{node}}"
    }
   ]
  },
  {
   "title": "Scheduler Preemption Attempts Total",
   "type": "graph",
   "description": "for the PodPriority bug",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_total_preemption_attempts"
    }
   ]
  }
 ]
}