{
 "title": "Pach-Image-Process-Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pach Image Decode Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_processor_decoder_count{service=~\"engine-ips-worker-pach-.*\"}[10m])) by (name, state)"
    }
   ]
  },
  {
   "title": "Async Pach Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(struct_async_extract_process_duration{service=~\"engine-ips-worker-pach-.*\"}) by (quantile, type)"
    }
   ]
  },
  {
   "title": "Sync Pach Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(struct_extract_process_duration{service=~\"engine-ips-worker-pach-.*\"}) by (quantile, type)"
    }
   ]
  },
  {
   "title": "Async Pach Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_process_stream_producer{service=~\"engine-ips-worker-pach-.*\"}[10m])) by (pod, type, tag)"
    }
   ]
  },
  {
   "title": "Sync Pach Processing Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(struct_extract_image_failed{service=~\"engine-ips-worker-pach-.*\"}[10m])) by (reason)"
    }
   ]
  },
  {
   "title": "Async Pach Processing Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(struct_extract_image_processed_error{service=~\"engine-ips-worker-pach-.*\"}[10m])) by (reason)"
    }
   ]
  },
  {
   "title": "Sync Pach Processing Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(struct_images_success_processed{service=~\"engine-ips-worker-pach-.*-svc\"}[10m])) by (pod)"
    }
   ]
  },
  {
   "title": "Processors Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_processor_detail_duration{service=~\"engine-ips-worker-pach-.*\"}) by (quantile, name)"
    }
   ]
  }
 ]
}