{
 "title": "Engine / Image-Egress-Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ObjectPut Total Success Count",
   "type": "graph",
   "description": "Total egress objectput requests success count by platform deviceID",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_egress_put_requests_success) by (platformID)",
     "legendFormat": "{{platformID}}"
    }
   ]
  },
  {
   "title": "ObjectPut Success Rate (sec)",
   "type": "graph",
   "description": "Total egress objectput requests success count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_egress_put_requests_success[5m])) by (platformID)",
     "legendFormat": "{{platformID}}"
    }
   ]
  },
  {
   "title": "ObjectPut Total Failed Count",
   "type": "graph",
   "description": "Total egress objectput failed count by reason",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_egress_put_requests_dropped) by (platformID, reason)",
     "legendFormat": "{{platformID}} {{reason}}"
    }
   ]
  },
  {
   "title": "ObjectPut Failed Rate (sec)",
   "type": "graph",
   "description": "Total egress objectput failed count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_egress_put_requests_dropped[5m])) by (platformID, reason)",
     "legendFormat": "{{platformID}} {{reason}}"
    }
   ]
  },
  {
   "title": "ObjectPut Step Duration Rate(sec)",
   "type": "graph",
   "description": "Time duration of putting object in each step",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_egress_put_object_process_duration) by (type, quantile)"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_egress_object_process_duration) by (type, quantile)"
    }
   ]
  },
  {
   "title": "Messages Received Rate (sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_egress_mq_message_received[5m])) by (collType)",
     "legendFormat": "{{collType}}-[1:Kafka, 2:Grpc, 3:StructDB]"
    }
   ]
  },
  {
   "title": "Total Received Messages (Offset)",
   "type": "graph",
   "description": "The total number of received messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_egress_mq_message_received) by (collType)",
     "legendFormat": "{{collType}}-[1:Kafka, 2:Grpc, 3:StructDB]"
    }
   ]
  },
  {
   "title": "Messages Dropped Rate (sec)",
   "type": "graph",
   "description": "Number of messages dropped",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_egress_message_dropped[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Total Dropped Messages (Offset)",
   "type": "graph",
   "description": "Total drop egress messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_egress_message_dropped) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Messages Pushed Rate (sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_egress_message_sent[5m])) by (platID)",
     "legendFormat": "{{platID}}"
    }
   ]
  },
  {
   "title": "Total Pushed Messages (Offset)",
   "type": "graph",
   "description": "Total pushed messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_egress_message_sent) by (platID)",
     "legendFormat": "{{platID}}"
    }
   ]
  },
  {
   "title": "Channel Buffer Usage: coll -> input -> filter -> download -> push",
   "type": "graph",
   "description": "Size and useage of channel buffer.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(image_egress_service_cache_used) / (image_egress_service_cache_size)",
     "legendFormat": "{{cacheName}}.{{pod}}"
    },
    { "expr": "80/100", "legendFormat": "threshold" }
   ]
  }
 ]
}