{
 "title": "Engine / Video-Process-Service-Algo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": "label_values(kube_deployment_labels{label_app=\"vps-algoapp\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{pod=~\"$Type.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "mem usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{pod=\"$pod\",container!=\"POD\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=\"$pod\"}",
     "legendFormat": "Requested: {{ container }}"
    }
   ]
  },
  {
   "title": "duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(video_process_worker_process_durations{pod=~\"$Type-.*\"}) by (step)",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "frame pool size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "video_process_worker_allocatable_frames{pod=~\"$Type-.*\"}",
     "legendFormat": "{{pod}}-{{taskID}}"
    }
   ]
  },
  {
   "title": "TaskCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_process_worker_tasks{pod=~\"$Type-.*\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "decoder queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "video_process_worker_queue_length{type=\"decoder\",pod=~\"$Type-.*\"}",
     "legendFormat": " {{pod}}-{{taskID}}-{{type}} "
    },
    {
     "expr": "video_process_worker_queue_length{type=~\"outputer-.*\",pod=~\"$Type-.*\"}",
     "legendFormat": "{{pod}}-{{type}} "
    },
    {}
   ]
  },
  {
   "title": "Drop Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_process_worker_objects_dropped{step=\"decoder\",type=\"frame\",pod=~\"$Type-.*\"}[1m]))/sum(irate(video_process_worker_objects_processed{step=\"decoder\",type=\"frame\",pod=~\"$Type-.*\"}[1m]))",
     "legendFormat": "frames drop rate[1m]"
    },
    {
     "expr": "sum(rate(video_process_worker_objects_dropped{step=\"decoder\",type=\"frame\",pod=~\"$Type-.*\"}[10m]))/sum(rate(video_process_worker_objects_processed{step=\"decoder\",type=\"frame\",pod=~\"$Type-.*\"}[10m]))",
     "legendFormat": "frames drop rate[10m]"
    },
    {
     "expr": "sum(rate(video_process_worker_objects_dropped{step=\"outputer\",pod=~\"$Type-.*\"}[1m]))/(sum(rate(video_process_worker_objects_dropped{step=\"outputer\",pod=~\"$Type-.*\"}[1m])) + sum(rate(video_process_worker_objects_processed{step=\"outputer\",pod=~\"$Type-.*\"}[1m])))",
     "legendFormat": "results drop rate[outputer -> ]"
    }
   ]
  },
  {
   "title": "Frames Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_process_worker_objects_processed{step=\"decoder\",type=\"packet\",pod=~\"$Type-.*\"}[1m]))/sum(video_process_worker_tasks{pod=~\"$Type-.*\"})",
     "legendFormat": "packets_decoder_read"
    },
    {
     "expr": "sum(irate(video_process_worker_objects_processed{step=\"decoder\",type=\"frame\",pod=~\"$Type-.*\"}[1m]))/sum(video_process_worker_tasks{pod=~\"$Type-.*\"})",
     "legendFormat": "frames_decoded"
    },
    {
     "expr": "sum(irate(video_process_worker_objects_dropped{step=\"decoder\",type=\"frame\",pod=~\"$Type-.*\"}[1m]))/sum(video_process_worker_tasks{pod=~\"$Type-.*\"})",
     "legendFormat": "frames_decoder_dropped"
    },
    {
     "expr": "sum(irate(video_process_worker_objects_processed{step=\"reader\",type=\"packet\",pod=~\"$Type-.*\"}[1m]))/sum(video_process_worker_tasks{pod=~\"$Type-.*\"})",
     "legendFormat": "packets_demuxer_read"
    }
   ]
  },
  {
   "title": "Results Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_process_worker_objects_processed{type!~\"(packet|frame)\",pod=~\"$Type-.*\"}[1m])) by (step,type)",
     "legendFormat": "results_{{step}}_{{type}}"
    },
    {
     "expr": "sum(irate(video_process_worker_objects_dropped{type!~\"(packet|frame)\",pod=~\"$Type-.*\"}[1m])) by (step,type)",
     "legendFormat": "results_{{step}}_{{type}}_dropped"
    }
   ]
  }
 ]
}