{
 "title": "Engine / Alert-Feature-DB",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db_type", "query": "afd" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "特征库收到的所有请求数量。\n\n折线：每秒收到的请求数量。\n\n蓝柱：每秒成功处理的请求数量。\n\n红柱：每秒处理失败的请求数量。\n\n灰柱：超时的请求数量。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_code=~\"OK|Canceled\"}[1m])) by (service)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_code=\"DeadlineExceeded\"}[1m])) by (service)",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_code!~\"DeadlineExceeded|Canceled|OK\"}[1m])) by (service)",
     "legendFormat": "Fail"
    },
    {
     "expr": "sum(rate(grpc_server_started_total{service=~\"$db_type-proxy\"}[1m])) by (service)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pod",
   "type": "stat",
   "description": "正常运行的组件数量。\n\nproxies：正常运行的proxy节点数量。\n\nmasters：正常运行的master节点数量。\n\nslaves：正常运行的slave节点数量。",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"$db_type-proxy-.*\"})",
     "legendFormat": "proxies"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"$db_type-worker-.*-0\"})",
     "legendFormat": "masters"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"$db_type-worker-.*-[1-9]*\"})",
     "legendFormat": "slaves"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "graph",
   "description": "每个worker上的索引数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "indexes" }
   ],
   "targets": [
    {
     "expr": "sum(static_feature_worker_index_count{pod=~\"$db_type-worker-.*-0\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Features",
   "type": "graph",
   "description": "每个worker存储的特征数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "features" }
   ],
   "targets": [
    {
     "expr": "sum(static_feature_worker_index_size{service=~\"$db_type-worker-.*\"}) by(service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Porxy CPU",
   "type": "graph",
   "description": "proxy节点的CPU资源状态",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=~\"$db_type-proxy\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=~\"$db_type-proxy\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"$db_type-proxy\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "description": "worker节点的内存资源状态",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=~\"$db_type-worker\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=~\"$db_type-worker\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"$db_type-worker\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Porxy Memory",
   "type": "graph",
   "description": "proxy节点的内存资源状态",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=~\"$db_type-proxy\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=~\"$db_type-proxy\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"$db_type-proxy\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Worker Memory",
   "type": "graph",
   "description": "worker节点的内存资源状态",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=~\"$db_type-worker\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=~\"$db_type-worker\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"$db_type-worker\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Feature Add", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Feature Add Requests",
   "type": "graph",
   "description": "特征入库请求数量。\n\n折线：每秒收到的入库请求数量。\n\n蓝柱：每秒成功处理的入库请求数量。\n\n红柱：每秒入库失败的入库请求数量。\n\n灰柱：超时的入库请求数量。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchAdd\", grpc_code=~\"OK|Canceled\"}[1m])) by (service)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchAdd\", grpc_code=\"DeadlineExceeded\"}[1m])) by (service)",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchAdd\", grpc_code!~\"DeadlineExceeded|Canceled|OK\"}[1m])) by (service)",
     "legendFormat": "Fail"
    },
    {
     "expr": "sum(rate(grpc_server_started_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchAdd\"}[1m])) by (service)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Feature Indexing Latency",
   "type": "graph",
   "description": "为特征建立索引的时延",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_worker_gpu_operation_duration{service=~\"$db_type-worker-.*\", command=\"add\"}) by (service,quantile)",
     "legendFormat": "{{ service }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_worker_gpu_operation_duration_sum{service=~\"$db_type-worker-.*\", command=\"add\"}[1m])/rate(static_feature_worker_gpu_operation_duration_count{service=~\"$db_type-worker-.*\", command=\"add\"}[1m])",
     "legendFormat": "{{ service }}/mean"
    }
   ]
  },
  {
   "title": "Features persisting Latency",
   "type": "graph",
   "description": "特征插入持久化数据库的时延",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_worker_cassandra_operation_duration{service=~\"$db_type-worker-.*\", command=\"SaveFeatures\"}) by (service, quantile)",
     "legendFormat": "{{ service }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_worker_cassandra_operation_duration_sum{service=~\"$db_type-worker-.*\", command=\"SaveFeatures\"}[1m])/rate(static_feature_worker_cassandra_operation_duration_count{command=\"SaveFeatures\"}[1m])",
     "legendFormat": "{{ service }}/mean"
    }
   ]
  },
  { "title": "Feature Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Feature Search Requests",
   "type": "graph",
   "description": "特征库收到的搜索请求数量。\n\n折线：每秒收到的搜索请求数量。\n\n蓝柱：每秒成功处理的搜索请求数量。\n\n红柱：每秒搜索失败的搜索请求数量。\n\n灰柱：超时的搜索请求数量。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchSearch(Multi)?\", grpc_code=~\"OK|Canceled\"}[1m])) by (service)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchSearch(Multi)?\", grpc_code=\"DeadlineExceeded\"}[1m])) by (service)",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchSearch(Multi)?\", grpc_code!~\"DeadlineExceeded|Canceled|OK\"}[1m])) by (service)",
     "legendFormat": "Fail"
    },
    {
     "expr": "sum(rate(grpc_server_started_total{service=~\"$db_type-proxy\", grpc_method=~\"FeatureBatchSearch(Multi)?\"}[1m])) by (service)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Indexes searching Latency",
   "type": "graph",
   "description": "索引表中搜索特征的时延",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_worker_gpu_operation_duration{service=~\"$db_type-worker-.*\", command=\"search\"}) by (pod,quantile)",
     "legendFormat": "{{ pod }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_worker_gpu_operation_duration_sum{service=~\"$db_type-worker-.*\", command=\"search\"}[1m])/rate(static_feature_worker_gpu_operation_duration_count{service=~\"$db_type-worker-.*\", command=\"search\"}[1m])",
     "legendFormat": "{{ pod }}/mean"
    }
   ]
  },
  {
   "title": "Feature Searching Latency",
   "type": "graph",
   "description": "特征搜索的时延",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_proxy_feature_worker_search_duration{job=~\"$db_type-proxy\"}) by (pod,quantile)",
     "legendFormat": "{{ pod }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_proxy_feature_worker_search_duration_sum{job=~\"$db_type-proxy\"}[1m])/rate(static_feature_proxy_feature_worker_search_duration_count{job=~\"$db_type-proxy\"}[1m])",
     "legendFormat": "{{ pod }}/mean"
    }
   ]
  },
  {
   "title": "Worker Searching Latency",
   "type": "graph",
   "description": "worker搜索时延",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_worker_search_duration{service=~\"$db_type-worker-.*\"}) by (pod, quantile)",
     "legendFormat": "{{ pod }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_worker_search_duration_sum{service=~\"$db_type-worker-.*\"}[1m])/rate(static_feature_worker_search_duration_count{service=~\"$db_type-worker-.*\"}[1m])",
     "legendFormat": "{{ pod }}/mean"
    }
   ]
  },
  {
   "title": "Proxy refine Latency",
   "type": "graph",
   "description": "proxy节点精搜时延",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_proxy_refine_duration{service=~\"$db_type-proxy\"}) by (pod, quantile)",
     "legendFormat": "{{ pod }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_proxy_refine_duration_sum{service=~\"$db_type-proxy\"}[1m])/rate(static_feature_proxy_refine_duration_count{service=~\"$db_type-proxy\"}[1m])",
     "legendFormat": "{{ pod }}/mean"
    }
   ]
  },
  {
   "title": "Persistence Reading during Proxy Refine Latency",
   "type": "graph",
   "description": "proxy节点精搜时从持久化数据库读取长特征的时延",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_proxy_feature_cassandra_select_duration{service=~\"$db_type-proxy\"}) by (pod, quantile)",
     "legendFormat": "{{ pod }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_proxy_feature_cassandra_select_duration_sum{service=~\"$db_type-proxy\"}[1m])/rate(static_feature_proxy_feature_cassandra_select_duration_count{service=~\"$db_type-proxy\"}[1m])",
     "legendFormat": "{{ pod }}/mean"
    }
   ]
  },
  {
   "title": "Worker Refine Latency",
   "type": "graph",
   "description": "worker节点精搜时延",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_worker_refine_duration{service=~\"$db_type-worker-.*\"}) by (pod,quantile)",
     "legendFormat": "{{ pod }}/{{ quantile }}"
    },
    {
     "expr": "rate(static_feature_worker_refine_duration_sum{service=~\"$db_type-worker-.*\"}[1m])/rate(static_feature_worker_refine_duration_count{service=~\"$db_type-worker-.*\"}[1m])",
     "legendFormat": "{{ pod }}/mean"
    }
   ]
  },
  {
   "title": "Replicaset Searching Latency",
   "type": "graph",
   "description": "副本集搜索时延",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(static_feature_proxy_feature_each_worker_search_duration{service=~\"$db_type-proxy\"}) by (replicaset, quantile)",
     "legendFormat": "{{ replicaset }}/{{ quantile }}"
    },
    {
     "expr": "avg(rate(static_feature_proxy_feature_each_worker_search_duration_sum{service=~\"$db_type-proxy\"}[1m])/rate(static_feature_proxy_feature_each_worker_search_duration_count{service=~\"$db_type-proxy\"}[1m])) by (replicaset)",
     "legendFormat": "{{ replicaset }}/mean"
    }
   ]
  }
 ]
}