{
 "title": "Engine / timespace-face-Feature-DB-olap",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running pod",
   "type": "bargauge",
   "description": "running pod nums",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"})",
     "legendFormat": "coordinator-olap"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"})",
     "legendFormat": "reducer-olap"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"})",
     "legendFormat": "worker-olap"
    }
   ]
  },
  {
   "title": "Request",
   "type": "graph",
   "description": "system request, such as success nums, cancel nums",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_code=\"OK\"})",
     "legendFormat": "{Type: OK}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_code=\"DeadlineExceeded\"})",
     "legendFormat": "{Type: Timeout}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_code=\"Canceled\"})",
     "legendFormat": "{Type: Cancel}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_code!~\"OK|Canceled|DeadlineExceeded\"}) ",
     "legendFormat": "{Type: Other}"
    }
   ]
  },
  {
   "title": "cluster indexes",
   "type": "graph",
   "description": "cluster-indexes of each worker",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(search_worker_index_count{job=\"engine-tsfd-face-olap-worker\",type=\"cluster\"})",
     "legendFormat": "total"
    },
    {
     "expr": "search_worker_index_count{job=\"engine-tsfd-face-olap-worker\",type=\"cluster\"}",
     "legendFormat": "{Pod:{{ pod }}}"
    }
   ]
  },
  {
   "title": "clusters",
   "type": "graph",
   "description": "clusters of each worker",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(search_worker_index_size{job=\"engine-tsfd-face-olap-worker\"})",
     "legendFormat": "total"
    },
    {
     "expr": "search_worker_index_size{job=\"engine-tsfd-face-olap-worker\"}",
     "legendFormat": "{Pod: {{ pod }}}"
    }
   ]
  },
  {
   "title": "Cluster Search Count",
   "type": "graph",
   "description": "details of cluster-search , such success nums, cancel nums...",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\",grpc_code=\"OK\"})",
     "legendFormat": "{Type: OK}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\",grpc_code=\"Canceled\"})",
     "legendFormat": "{Type: Canceled}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\",grpc_code=\"DeadlineExceeded\"})",
     "legendFormat": "{Type: Timeout}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\",grpc_code=\"DeadlineExceeded\"})",
     "legendFormat": "{Type: InvalidArgument}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\",grpc_code!~\"OK|Canceled|DeadlineExceeded|InvalidArgument\"})",
     "legendFormat": "{Type: Other}"
    }
   ]
  },
  {
   "title": "cluster search rate",
   "type": "graph",
   "description": "the rate of cluster-search request",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\"}[1m]))",
     "legendFormat": "{Type: Avg}"
    },
    {
     "expr": "rate(grpc_server_handled_total{job=\"engine-tsfd-face-olap-reducer\",grpc_method=\"ClusterSearch\"}[1m])",
     "legendFormat": "{Type: One, Pod: {{pod}}}"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reducer Memory",
     "type": "graph",
     "description": "memory details of reducer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Used, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Limit, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"} / 1000000000 ",
       "legendFormat": "{Type: Request, Pod: {{pod}}}"
      }
     ]
    },
    {
     "title": "Reducer Cpu",
     "type": "graph",
     "description": "cpu details of reducer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"} [1m])",
       "legendFormat": "{Type: Used, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"}",
       "legendFormat": "{Type: Limit, Pod: {{pod}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-reducer\",pod=~\".*-olap-.*\"}",
       "legendFormat": "{Type: Request, Pod: {{pod}}}"
      }
     ]
    },
    {
     "title": "Coor Memory",
     "type": "graph",
     "description": "memory details of coordinator",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Used, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Limit, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"} / 1000000000 ",
       "legendFormat": "{Type: Request, Pod: {{pod}}}"
      }
     ]
    },
    {
     "title": "Coor CPU",
     "type": "graph",
     "description": "cpu details of coordinator",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"} [1m])",
       "legendFormat": "{Type: Used, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"}",
       "legendFormat": "{Type: Limit, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-coor\",pod=~\".*-olap-.*\"}",
       "legendFormat": "{Type: Request, Pod: {{pod}}}"
      }
     ]
    },
    {
     "title": "Worker Memory",
     "type": "graph",
     "description": "memory details of worker",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Used, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Limit, Pod: {{pod}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"} / 1000000000",
       "legendFormat": "{Type: Request, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "Worker CPU",
     "type": "graph",
     "description": "cpu details of worker",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"} [1m])",
       "legendFormat": "{Type: Used, Pod: {{pod}}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"}",
       "legendFormat": "{Type: Limit, Pod: {{pod}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-worker\",pod=~\".*-olap-.*\"}",
       "legendFormat": "{Type: Request, Pod: {{pod}}}"
      }
     ]
    }
   ]
  },
  { "title": "Oplog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Oplog consume success count",
   "type": "graph",
   "description": "success num of oplog consuming",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oplog_add_feature_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: add_features}"
    },
    {
     "expr": "sum(oplog_add_index_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: add_index}"
    },
    {
     "expr": "sum(oplog_del_feature_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: delete_feature}"
    },
    {
     "expr": "sum(oplog_delete_clusterid_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: delete_feature_clusterId}"
    },
    {
     "expr": "sum(oplog_add_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: add_cluster}"
    },
    {
     "expr": "sum(oplog_del_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: delete_cluster}"
    },
    {
     "expr": "sum(oplog_update_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: update_cluster}"
    },
    {
     "expr": "sum(oplog_update_cluster_user_key_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: update_cluster_user_key}"
    },
    {
     "expr": "sum(oplog_delete_cluster_user_key_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: delete_cluster_user_key}"
    },
    {
     "expr": "sum(oplog_merge_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: merge_cluster}"
    },
    {
     "expr": "sum(oplog_update_cluster_preview_image_consume_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "{Type: update_cluster_preview_image}"
    }
   ]
  },
  {
   "title": "Oplog consume failed count",
   "type": "graph",
   "description": "the failed num of oplog consuming",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oplog_consume_failed_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "total"
    },
    {
     "expr": "oplog_consume_failed_count{job=\"engine-tsfd-face-olap-coor\"}",
     "legendFormat": "{Reason: {{reason}}, Pod: {{pod}}}"
    }
   ]
  },
  {
   "title": "Oplog consume rate",
   "type": "graph",
   "description": "the rate of oplog consuming",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oplog_add_feature_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: add_feature}"
    },
    {
     "expr": "rate(oplog_add_index_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: add_index}"
    },
    {
     "expr": "rate(oplog_update_clusterid_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type; update_feature_clusterId}"
    },
    {
     "expr": "rate(oplog_del_feature_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: delete_feature}"
    },
    {
     "expr": "rate(oplog_delete_clusterid_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: delete_feature_clusterId}"
    },
    {
     "expr": "rate(oplog_add_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: add_cluster}"
    },
    {
     "expr": "rate(oplog_del_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: delete_cluster}"
    },
    {
     "expr": "rate(oplog_update_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: update_cluster}"
    },
    {
     "expr": "rate(oplog_update_cluster_user_key_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: update_cluster_user_key}"
    },
    {
     "expr": "rate(oplog_delete_cluster_user_key_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: delete_cluster_user_key}"
    },
    {
     "expr": "rate(oplog_merge_cluster_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: merge_cluster}"
    },
    {
     "expr": "rate(oplog_update_cluster_preview_image_consume_count{job=\"engine-tsfd-face-olap-coor\"} [5m])",
     "legendFormat": "{Type: update_cluster_preview_image}"
    }
   ]
  },
  {
   "title": "cassandra latency of oplog operation",
   "type": "graph",
   "description": "cassandra latnecy of oplog",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oplog_cassandra_operation_duration{job=\"engine-tsfd-face-olap-coor\"}",
     "legendFormat": "{Type: {{type}}, Pod: {{ pod }},  Quantile:{{ quantile }}}"
    }
   ]
  },
  {
   "title": "oplog operation failed information",
   "type": "graph",
   "description": "it only means one operation failed, not oplog consume failed",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oplog_operation_failed_count{job=\"engine-tsfd-face-olap-coor\"})",
     "legendFormat": "total"
    },
    {
     "expr": "oplog_operation_failed_count{job=\"engine-tsfd-face-olap-coor\"}",
     "legendFormat": "{Type: {{type}}, Reason: {{reason}}, Pod:{{pod}}}"
    }
   ]
  }
 ]
}