{
 "title": "Engine / Video-Ingress-Service",
 "description": " Video Ingress Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Ingress Sources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_ingress_worker_sources)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(video_ingress_worker_sources) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Egress Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(video_ingress_worker_egress_sessions)",
     "legendFormat": "total",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(video_ingress_worker_egress_sessions) by (instance)",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Ingress Sources Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_ingress_worker_sources_failed) by (reasonType)",
     "legendFormat": "{{reasonType}}"
    }
   ]
  },
  {
   "title": "Egress Packet Dropped Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_ingress_worker_drop_bytes[1m]))/sum(irate(video_ingress_worker_ingress_bytes[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Ingress Packet Dropped Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_ingress_worker_ingress_drop_packets{}[1m]))/sum(irate(video_ingress_worker_ingress_packets{}[1m]))",
     "legendFormat": "packet drop rate[1m]"
    },
    {
     "expr": "sum(rate(video_ingress_worker_ingress_drop_packets{}[5m]))/sum(rate(video_ingress_worker_ingress_packets{}[5m]))",
     "legendFormat": "packet drop rate[5m]"
    },
    {
     "expr": "sum(rate(video_ingress_worker_ingress_drop_packets{}[10m]))/sum(rate(video_ingress_worker_ingress_packets{}[10m]))",
     "legendFormat": "packet drop rate[10m]"
    }
   ]
  },
  {
   "title": "Stream I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_ingress_worker_ingress_bytes[1m]))",
     "legendFormat": "ingress"
    },
    {
     "expr": "sum(irate(video_ingress_worker_egress_bytes[1m]))",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Ingress Source Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_ingress_worker_sources) by (sourceType)",
     "legendFormat": "{{sourceType}}"
    }
   ]
  },
  {
   "title": "Ingress Codec Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_ingress_worker_sources) by (codecType)",
     "legendFormat": "{{codecType}}"
    }
   ]
  },
  {
   "title": "Ingress Transport Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_ingress_worker_sources{transportType=~\"TCP|TCP_SERVER_MODE\"})",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(video_ingress_worker_sources{transportType=\"UDP\"})",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Ingress Frames Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(video_ingress_worker_ingress_frames[1m])) / sum(video_ingress_worker_sources)",
     "legendFormat": "ingress FPS"
    }
   ]
  },
  {
   "title": "Ingress Sources Resolution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(video_ingress_worker_sources) by (resolution)",
     "legendFormat": "{{resolution}}"
    }
   ]
  }
 ]
}