{
 "title": "Engine / Struct-DB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "kafka messages processed(24h)",
   "type": "singlestat",
   "description": "messages from kafka processed in the latest 24h",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(struct_db_message_processed{}[24h]))"
    }
   ]
  },
  {
   "title": "indices total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(count(struct_db_es_indices_index_total{index!=\"all\"}) by (pod))"
    }
   ]
  },
  {
   "title": "docs total",
   "type": "singlestat",
   "description": "total docs in es",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(struct_db_es_indices_docs_count{index=\"all\"})"
    }
   ]
  },
  {
   "title": "es storage used percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": " avg(struct_db_es_storage_used) / avg(struct_db_es_storage_total)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"engine-struct-db-server\", grpc_code=~\"OK|Canceled\"}[1m])) by (service)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"engine-struct-db-server\", grpc_code=\"DeadlineExceeded\"}[1m])) by (service)",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{service=~\"engine-struct-db-server\", grpc_code!~\"DeadlineExceeded|Canceled|OK\"}[1m])) by (service)",
     "legendFormat": "Fail"
    },
    {
     "expr": "sum(rate(grpc_server_started_total{service=~\"engine-struct-db-server\"}[1m])) by (service)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"engine-struct-db-server-.*\"})",
     "legendFormat": "struct-db-server"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"engine-struct-db-transformer-.*\"})",
     "legendFormat": "struct-db-transformer"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"es-data-default-[0-9]*\"})",
     "legendFormat": "es"
    }
   ]
  },
  { "title": "consume & add", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "kafka messages process rate(message per sec)",
   "type": "graph",
   "description": "the rate of consuming messages from kafka",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(struct_db_message_processed{}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(struct_db_message_processed{}[5m])) by (service)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "gRPC  query&aggregate  rate(qps)",
   "type": "graph",
   "description": "gRPC server handling QPS by method",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{service=\"engine-struct-db-server\",grpc_method=\"Query\"}[5m]) /rate(grpc_server_handling_seconds_count{service=\"engine-struct-db-server\",grpc_method=\"Query\"}[5m]))",
     "legendFormat": "query"
    },
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{service=\"engine-struct-db-server\",grpc_method=\"Aggregate\"}[5m]) /rate(grpc_server_handling_seconds_count{service=\"engine-struct-db-server\",grpc_method=\"Aggregate\"}[5m]))",
     "legendFormat": "aggregate"
    }
   ]
  },
  {
   "title": "struct-db-server Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=~\"engine-struct-db-server\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=~\"engine-struct-db-server\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"engine-struct-db-server\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "struct-db-server CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=~\"engine-struct-db-server\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=~\"engine-struct-db-server\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"engine-struct-db-server\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "struct-db-transformer Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=~\"engine-struct-db-transformer\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=~\"engine-struct-db-transformer\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"engine-struct-db-transformer\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "struct-db-transformer CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=~\"engine-struct-db-transformer\"}",
     "legendFormat": "{{ pod }}/limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=~\"engine-struct-db-transformer\"}",
     "legendFormat": "{{ pod }}/request"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"engine-struct-db-transformer\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "messages processed",
   "type": "graph",
   "description": "object info messages consumed from kafka and indexed",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(struct_db_message_processed{}) by (pod)",
     "legendFormat": "{{ pod }}/consumed"
    },
    {
     "expr": "sum(struct_db_message_processed{result=\"put_success\"}) by (pod)",
     "legendFormat": "Messages send to ES success, {{pod}}"
    },
    {
     "expr": "sum(struct_db_message_processed{result=\"put_failed\"}) by (pod)",
     "legendFormat": "Messages send to ES failed, {{pod}}"
    },
    {
     "expr": "sum(struct_db_message_processed{result=\"parse_failed\"}) by (pod)",
     "legendFormat": "Messages  parse failed, {{pod}}"
    },
    {
     "expr": "sum(struct_db_message_processed{result=\"parse_skipped\"}) by (pod)",
     "legendFormat": "Messages  parse skipped, {{pod}}"
    }
   ]
  },
  {
   "title": "storage used(indices top 5)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(struct_db_es_indices_store{index=\"all\"})",
     "legendFormat": "storage used total"
    },
    {
     "expr": "topk(5, avg(struct_db_es_indices_store{index!=\"all\"})by(index))",
     "legendFormat": "{{index}} used"
    }
   ]
  },
  {
   "title": "write es latency",
   "type": "graph",
   "description": "time cost of indexing a batch of objects",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(struct_db_es_write_latency{service=\"engine-struct-db-transformer\",quantile!=\"0.5\"}) by (pod, quantile)"
    },
    {
     "expr": "rate(struct_db_es_write_latency_sum[5m])/rate(struct_db_es_write_latency_count[5m])",
     "legendFormat": "average_latency-{{pod}}"
    }
   ]
  },
  { "title": "query & aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "ES query latency",
   "type": "graph",
   "description": "elasticsearch query latency of quantile 0.9 and 0.99",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "struct_db_es_search_latency{action=\"query\",quantile!=\"0.5\"}",
     "legendFormat": "{pod={{pod}}, quantile={{quantile}}}"
    }
   ]
  },
  {
   "title": "ES aggregate latency",
   "type": "graph",
   "description": "elasticsearch aggregate latency at quantile 0.9/0.99",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "struct_db_es_search_latency{action=\"nested_aggregate\",quantile!~\"0.5\"}",
     "legendFormat": "{action={{action}}, pod={{pod}}, quantile={{quantile}}}"
    },
    {
     "expr": "struct_db_es_search_latency{action=\"flatted_aggregate\", quantile!~\"0.5\"}",
     "legendFormat": "{action={{action}}, pod={{pod}}, quantile={{quantile}}}"
    }
   ]
  },
  {
   "title": "parse search result latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(struct_db_es_search_latency{action=~\"parse_.*\"}) by(job, quantile)"
    },
    {}
   ]
  }
 ]
}