{
 "title": "Engine / Protocol-Ingress-Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Devices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(protocol_ingress_worker_devices)"
    }
   ]
  },
  {
   "title": "GB28181 Streams",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(protocol_ingress_worker_gb28181_streams)"
    }
   ]
  },
  {
   "title": "Device Catalog Items",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(protocol_ingress_worker_catalogs) by (deviceUUID)"
    }
   ]
  },
  {
   "title": "Device Catalog Duration Rate(sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(protocol_ingress_worker_catalog_duration) by (deviceUUID)"
    }
   ]
  },
  {
   "title": "GB28181 Local Configs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(protocol_ingress_worker_gb28181_local_configs)"
    }
   ]
  }
 ]
}