{
 "title": "Engine / Entity-Service-ETL",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Data Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Remain Batch Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(etl_total_batch_count_gauge{data_source_type=\"fs\"}-etl_current_batch_index_gauge{data_source_type=\"fs\"}) by (data_source)",
     "legendFormat": "{{data_source}}"
    }
   ]
  },
  {
   "title": "Transformer Quantity Processed OpLog  Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etl_clustering_op_log_type_counter[10m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "clustering oplog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etl_clustering_op_log_type_counter) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Consumer Quantity Processed OpLog  Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etl_consumer_clustering_op_log_type_counter[10m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "FS Data Source Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (data_source) (etl_processed_feature_captured_time_gauge{data_source_type=\"fs\"})",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum by (data_source) (etl_current_timestamp_gauge{data_source_type=\"fs\"})",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum by (data_source) (etl_latest_batch_timestamp_gauge{data_source_type=\"fs\"})",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum by (data_source)(etl_total_batch_count_gauge{data_source_type=\"fs\"}-etl_current_batch_index_gauge{data_source_type=\"fs\"})",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum by (data_source)(etl_total_batch_count_gauge{data_source_type=\"fs\"})",
     "legendFormat": "{{data_source}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Data Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(etl_clustering_op_log_type_counter) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_graph_operation_type_counter) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_tracks_operation_type_counter) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_tran_graph_operation_error_counter) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_tran_tracks_operation_error_counter) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_entity_service_info_counter{type=\"entityAnonymousAdd\"}) by (data_source) - sum(etl_entity_service_info_counter{type=\"entityAnonymousDelete\"}) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_entity_service_info_counter{type=\"entityIdentifiedAdd\"}) by (data_source) - sum(etl_entity_service_info_counter{type=\"entityIdentifiedDelete\"}) by (data_source)",
     "legendFormat": "{{data_source}}"
    },
    {
     "expr": "sum(etl_tracks_operation_type_counter{type=\"trackOperationAdd\"}) by (data_source) - sum(etl_tracks_operation_type_counter{type=\"trackOperationDel\"}) by (data_source)"
    }
   ]
  },
  { "title": "Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etl_clustering_op_log_type_gauge)/(sum(etl_transformer_time_cost_gauge)/1000)",
     "legendFormat": "clustering_oplog"
    }
   ]
  },
  {
   "title": "time cost(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(etl_transformer_time_cost_gauge) by (type)) / 1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "clustering oplog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(etl_clustering_op_log_type_counter[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cassandra Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etl_cassandra_query_type_counter) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}