{
 "title": "Engine / Short-Video-Storage-Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(short_video_storage_service_task_total)"
    }
   ]
  },
  {
   "title": "Prerecord Video Sources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(short_video_storage_service_prerecord_total)"
    }
   ]
  },
  {
   "title": "Prerecord Cache Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(short_video_storage_service_stream_cache_bytes)"
    }
   ]
  },
  {
   "title": "Prerecord Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(short_video_storage_service_prerecord_bytes[1m]))"
    }
   ]
  },
  {
   "title": "Consumed Topic Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(short_video_storage_service_event_message_count)"
    }
   ]
  },
  {
   "title": "Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(short_video_storage_service_record_total [1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(short_video_storage_service_record_successed[1m]))",
     "legendFormat": "successed"
    },
    {
     "expr": "sum(increase(short_video_storage_service_record_failed[1m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Channel Buffer Useage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(short_video_storage_service_cache_used) / (short_video_storage_service_cache_size)",
     "legendFormat": "{{cache_name}}.{{pod}}"
    }
   ]
  }
 ]
}