{
 "title": "Engine / FacePed-Image-Process-Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Sync FacePed Processing Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(faceped_extract_processed{service=~\"engine-ips-worker-captureforfaceped-.*\"}[10m])) by (pod)"
    }
   ]
  },
  {
   "title": "Async FacePed Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ips_photo_storage_succeed{service=~\"engine-ips-worker-captureforfaceped-.*\",stage=\"kafka\"}[10m])) by (pod, topic)"
    },
    {
     "expr": "sum(rate(ips_photo_storage_failed{service=~\"engine-ips-worker-captureforfaceped-.*\",stage=\"kafka\"}[10m])) by (pod, topic)"
    }
   ]
  },
  {
   "title": "Async FacePed Input Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(capture_for_faceped_consume_count{service=~\"engine-ips-worker-captureforfaceped-.*\"}[10m])) by (tag)"
    }
   ]
  },
  {
   "title": "Sync FacePed Processing Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(faceped_extract_failed{service=~\"engine-ips-worker-captureforfaceped-.*\"}[10m])) by (reason)"
    }
   ]
  },
  {
   "title": "Processors Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_processor_detail_duration{service=~\"engine-ips-worker-captureforfaceped-.*\"}) by (quantile, name)"
    }
   ]
  },
  {
   "title": "Cupid Result Type Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_faceped_cupid_process_count{service=~\"engine-ips-worker-captureforfaceped-.*\"}[10m])) by (type)"
    }
   ]
  },
  {
   "title": "Async FacePed Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(capture_for_faceped_process_duration{service=~\"engine-ips-worker-captureforfaceped-.*\"}) by (quantile, tag)"
    }
   ]
  }
 ]
}