{
 "title": "Engine / Image-Ingress-Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Received Rate (sec)",
   "type": "graph",
   "description": "Number of messages received from device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_message_received[5m]))"
    }
   ]
  },
  {
   "title": "Messages Failed Rate (sec)",
   "type": "graph",
   "description": "Number of messages failed to parsed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_message_failed[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Snapshot Accepted Rate (sec)",
   "type": "graph",
   "description": "Number of snapshots been validate by tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_worker_snapshot_accepted[5m]))"
    }
   ]
  },
  {
   "title": "Snapshot Dropped Rate (sec)",
   "type": "graph",
   "description": "Number of snapshots been dropped",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_worker_snapshot_dropped[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Image Received Rate (sec)",
   "type": "graph",
   "description": "Number of images been validate by tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_image_received[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image Dropped Rate (sec)",
   "type": "graph",
   "description": "Number of images been dropped",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_image_dropped[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Image Success Rate (sec)",
   "type": "graph",
   "description": "Number of images been successfully pushed to mq",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_image_success[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image Failed Rate (sec)",
   "type": "graph",
   "description": "Number of images been dropped",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_image_failed[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "ActiveTasks",
   "type": "graph",
   "description": "connect by SDK",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_ingress_worker_tasks)"
    }
   ]
  },
  {
   "title": "ActiveConnected",
   "type": "graph",
   "description": "connected by SDK",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_ingress_worker_device_connected)"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_ingress_worker_snapshot_process_duration) by (type, quantile)"
    }
   ]
  },
  {
   "title": "GRPC Handle Rate (sec)",
   "type": "graph",
   "description": "Number of grpc requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_ingress_service_grpc_handle[5m])) by (functionName)",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "Channel Buffer Useage",
   "type": "graph",
   "description": "Size and useage of channel buffer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(image_ingress_service_cache_used) / (image_ingress_service_cache_size)",
     "legendFormat": "{{cacheName}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Cameras of Each Kafka Partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(increase(image_ingress_service_kafka_message_partition[5m])) by (partitionIdx,cameraID) > 0) by (partitionIdx)",
     "legendFormat": "{{partitionIdx}}"
    }
   ]
  },
  {
   "title": "Input Message Increase of Each Kafka Partition(1h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(increase(image_ingress_service_kafka_message_partition[1h])) by (partitionIdx))",
     "legendFormat": "{{partitionIdx}}"
    }
   ]
  }
 ]
}