{
 "title": "Engine / Engine-Algo-Store-Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Current Goroutines",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(go_goroutines{service=\"engine-algo-store-service\"})"
    }
   ]
  },
  {
   "title": "Total Applets",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    { "expr": "sum(algo_store_app_num)" }
   ]
  },
  {
   "title": "Total Instances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "targets": [
    { "expr": "sum(algo_store_instance_num)" }
   ]
  },
  {
   "title": "Current goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"engine-algo-store-service\"}) by (pod)"
    }
   ]
  },
  {
   "title": "GRPC Error Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{grpc_code!=\"OK\",service=\"engine-algo-store-service\"}) by (grpc_code, grpc_method)"
    }
   ]
  },
  {
   "title": "Applet Upload Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(algo_store_app_upload_lantency_sum{}[2m]) / rate(algo_store_app_upload_lantency_count{}[2m])) by(step)"
    }
   ]
  },
  {
   "title": "AppList GRPC Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{grpc_method=\"AppList\"}[2m])/rate(grpc_server_handling_seconds_count{grpc_method=\"AppList\"}[2m])) by (le)"
    }
   ]
  }
 ]
}