{
 "title": "Engine / timespace-face-Feature-DB",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running pod",
   "type": "bargauge",
   "description": "running pod nums",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"})",
     "legendFormat": "coordinator"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"})",
     "legendFormat": "reducer"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"})",
     "legendFormat": "worker"
    }
   ]
  },
  {
   "title": "Request",
   "type": "graph",
   "description": "system request, such as success nums, cancel nums",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_code=\"OK\"})",
     "legendFormat": "{Type: OK}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_code=\"DeadlineExceeded\"})",
     "legendFormat": "{Type: Timeout}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_code=\"Canceled\"})",
     "legendFormat": "{Type: Canceled}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_code!~\"OK|Canceled|DeadlineExceeded\"})",
     "legendFormat": "{Type: Other}"
    }
   ]
  },
  {
   "title": "coordinator consuming rate",
   "type": "graph",
   "description": "the rate of search-coordinator consuming from kafka",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_coordinator_consume_count{service=\"engine-tsfd-face-coor\"}[5m])",
     "legendFormat": "{Pod: {{pod}}}"
    }
   ]
  },
  {
   "title": "coordinator processing failed",
   "type": "graph",
   "description": "the failed num of search-coor consuming from kafka",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(search_coordinator_process_faileds{service=\"engine-tsfd-face-coor\"}) by (job)"
    }
   ]
  },
  {
   "title": "worker features added per second",
   "type": "graph",
   "description": "features added per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(search_worker_index_size{job=\"engine-tsfd-face-worker\"}[1m])) by (pod,le)"
    }
   ]
  },
  {
   "title": "indexes",
   "type": "graph",
   "description": "indexes of each worker",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(search_worker_index_count{job=\"engine-tsfd-face-worker\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(search_worker_index_count{job=\"engine-tsfd-face-worker\",type=\"feature\",retrain=\"yes\"})",
     "legendFormat": "{total, Type: train}"
    },
    {
     "expr": "sum(search_worker_index_count{job=\"engine-tsfd-face-worker\",type=\"feature\",retrain=\"no\"})",
     "legendFormat": "{total, Type: untrain}"
    },
    {
     "expr": "search_worker_index_count{job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{ Pod: {{pod}} }"
    },
    {
     "expr": "search_worker_index_count{job=\"engine-tsfd-face-worker\",type=\"feature\",retrain=\"yes\"}",
     "legendFormat": "{Type: train, Pod: {{pod}}"
    },
    {
     "expr": "search_worker_index_count{job=\"engine-tsfd-face-worker\",type=\"feature\",retrain=\"no\"}",
     "legendFormat": "{Type: untrain, Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "worker total features",
   "type": "graph",
   "description": "features of each worker",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(search_worker_index_size{job=\"engine-tsfd-face-worker\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(search_worker_index_size{job=\"engine-tsfd-face-worker\"}) by(pod)"
    },
    {
     "expr": "search_timespace_feature_db_size{job=\"engine-tsfd-face-coor\"}",
     "legendFormat": "{db_size, Pod: {{ pod }}}"
    },
    {
     "expr": "search_timespace_feature_db_capacity{job=\"engine-tsfd-face-coor\"}",
     "legendFormat": "{ db_capacity, Pod: {{ pod }} }"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Reducer Memory",
   "type": "graph",
   "description": "memory info of reducer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"} / 1000000000",
     "legendFormat": "{Type: Used, Pod: {{ pod }}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"} / 1000000000",
     "legendFormat": "{Type: Limit: Pod: {{ pod }}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"} / 1000000000 ",
     "legendFormat": "{Type: Request, Pod:{{ pod }}}"
    }
   ]
  },
  {
   "title": "Reducer CPU",
   "type": "graph",
   "description": "cpu info of reducer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"} [1m])",
     "legendFormat": " {Type: Used: Pod: {{ pod }}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"}",
     "legendFormat": "{Type: Limit: Pod: {{ pod }}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-reducer\",pod!~\".*-olap-.*\"}",
     "legendFormat": "{Type: Request: Pod: {{ pod }}}"
    }
   ]
  },
  {
   "title": "Coor Memory",
   "type": "graph",
   "description": "memory info of coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"} / 1000000000",
     "legendFormat": "{Type: Used, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"} / 1000000000",
     "legendFormat": "{Type: Limit, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"} / 1000000000 ",
     "legendFormat": "{Type: Request, Pod: {{ pod }}}"
    }
   ]
  },
  {
   "title": "Coor CPU",
   "type": "graph",
   "description": "cpu info of coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"} [1m])",
     "legendFormat": "{Type: Used, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"}",
     "legendFormat": "{Type: Limit, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-coor\",pod!~\".*-olap-.*\"}",
     "legendFormat": "{Type: Request, Pod: {{pod}}}"
    }
   ]
  },
  {
   "title": "Worker Memory",
   "type": "graph",
   "description": "memory info of worker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"} / 1000000000",
     "legendFormat": "{Type: Used, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"} / 1000000000",
     "legendFormat": "{Type: Limit, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"} / 1000000000 ",
     "legendFormat": "{Type: Request, Pod: {{pod}}}"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "description": "cpu info of worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"} [1m])",
     "legendFormat": "{Type: Used, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"}",
     "legendFormat": "{Type: Limit, Pod: {{pod}}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=\"engine-tsfd-face-worker\",pod!~\".*-olap-.*\"}",
     "legendFormat": "{Type: Request, Pod: {{pod}}}"
    }
   ]
  },
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "search request detail",
   "type": "graph",
   "description": "details of search request, such as success num, cancel num...",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\",grpc_code=\"OK\"})",
     "legendFormat": "{Type: OK}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\",grpc_code=\"Canceled\"})",
     "legendFormat": "{Type: Canceled}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\",grpc_code=\"DeadlineExceeded\"})",
     "legendFormat": "{Type: Timeout}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\",grpc_code=\"InvalidArgument\"})",
     "legendFormat": "{Type: InvalidArgument}"
    },
    {
     "expr": "sum(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\",grpc_code!~\"OK|Canceled|DeadlineExceeded|InvalidArgument\"})",
     "legendFormat": "{Type: Other}"
    }
   ]
  },
  {
   "title": "Search request rate",
   "type": "graph",
   "description": "the rate of search request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{job=\"engine-tsfd-face-reducer\",grpc_method=\"Search\"} [1m])",
     "legendFormat": "{ Pod: {{ pod }} }"
    }
   ]
  },
  {
   "title": "reducer rough search",
   "type": "graph",
   "description": "details of rough search",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_reducer_feature_worker_search_duration_sum{job=\"engine-tsfd-face-reducer\",type=\"feature\"}[1m]) / rate(search_reducer_feature_worker_search_duration_count{job=\"engine-tsfd-face-reducer\",type=\"feature\"}[1m])",
     "legendFormat": "{Type: Avg, Pod: {{pod}}, Ns: {{namespace}}, DbId: {{dbid}}}"
    },
    {
     "expr": "search_reducer_each_worker_search_duration{service=\"engine-tsfd-face-reducer\",type=\"feature\"}",
     "legendFormat": "{Type: One,  Pod: {{ pod }},  Quantile:{{ quantile }}}"
    },
    {
     "expr": "search_reducer_feature_worker_search_duration{service=\"engine-tsfd-face-reducer\",type=\"feature\"}",
     "legendFormat": "{Type: MaxOne, Pod: {{ pod }}, Quantile:{{ quantile }}}"
    }
   ]
  },
  {
   "title": "reducer refine search",
   "type": "graph",
   "description": "details of refine search",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_reducer_feature_refine_duration_sum{job=\"engine-tsfd-face-reducer\"} / search_reducer_feature_refine_duration_count{job=\"engine-tsfd-face-reducer\"}",
     "legendFormat": "{Type: Avg, Pod: {{pod}}, Ns: {{ namespace }}, DbId: {{ dbid }}}"
    },
    {
     "expr": "search_reducer_feature_refine_duration{service=\"engine-tsfd-face-reducer\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Quantile: {{ quantile }}}"
    }
   ]
  },
  {
   "title": "worker search duration",
   "type": "graph",
   "description": "index search duration",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_worker_gpu_operation_duration_sum{command='search',job=\"engine-tsfd-face-worker\"}[1m]) / rate(search_worker_gpu_operation_duration_count{command='search',job=\"engine-tsfd-face-worker\"}[1m])",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: GPU }"
    },
    {
     "expr": "search_worker_gpu_operation_duration{command='search',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: GPU, Quantile: {{ quantile }}}"
    },
    {
     "expr": "search_worker_cpu_operation_duration_sum{command='search',job=\"engine-tsfd-face-worker\"} / search_worker_cpu_operation_duration_count{command='search',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: CPU }"
    },
    {
     "expr": "search_worker_cpu_operation_duration{command='search',job=\"engine-tsfd-face-worker\",quantile=\"0.9\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: CPU, Quantile: {{ quantile }}}"
    }
   ]
  },
  {
   "title": "reducer cassandra select one duration",
   "type": "graph",
   "description": "duration of cassandra select one",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_reducer_feature_cassandra_select_one_duration_sum{job=\"engine-tsfd-face-reducer\",type=\"feature\"}[1m]) / rate(search_reducer_feature_cassandra_select_one_duration_count{job=\"engine-tsfd-face-reducer\",type=\"feature\"}[1m])",
     "legendFormat": "{Type: Avg, Pod:{{ pod }}}"
    },
    {
     "expr": "search_reducer_feature_cassandra_select_one_duration{job=\"engine-tsfd-face-reducer\",type=\"feature\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Quantile: {{ quantile }}}"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "worker gpu add duration",
   "type": "graph",
   "description": "gpu  duration of add feature",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_worker_gpu_operation_duration_sum{command='add',job=\"engine-tsfd-face-worker\"}[1m]) / rate(search_worker_gpu_operation_duration_count{command='add',job=\"engine-tsfd-face-worker\"}[1m])",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: GPU }"
    },
    {
     "expr": "search_worker_gpu_operation_duration{command='add',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: GPU, Quantile: {{ quantile }}}"
    },
    {
     "expr": "search_worker_cpu_operation_duration_sum{command='add',job=\"engine-tsfd-face-worker\"} / search_worker_cpu_operation_duration_count{command='add',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: CPU }"
    },
    {
     "expr": "search_worker_cpu_operation_duration{command='add',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: CPU, Quantile: {{ quantile }}}"
    }
   ]
  },
  {
   "title": "worker dump duration",
   "type": "graph",
   "description": "gpu duration of dump shards",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_worker_gpu_operation_duration_sum{job=\"engine-tsfd-face-worker\",command=\"dump_shards\"}[1m]) / rate(search_worker_gpu_operation_duration_count{job=\"engine-tsfd-face-worker\",command=\"dump_shards\"}[1m])",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: GPU }"
    },
    {
     "expr": "search_worker_gpu_operation_duration{job=\"engine-tsfd-face-worker\",command=\"dump_shards\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: GPU, Quantile: {{ quantile }}}"
    },
    {
     "expr": "search_worker_cpu_operation_duration_sum{job=\"engine-tsfd-face-worker\",command=\"dump_shards\"} /search_worker_cpu_operation_duration_count{job=\"engine-tsfd-face-worker\",command=\"dump_shards\"}",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: CPU }"
    },
    {
     "expr": "search_worker_cpu_operation_duration{job=\"engine-tsfd-face-worker\",command=\"dump_shards\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: CPU, Quantile: {{ quantile }}}"
    }
   ]
  },
  {
   "title": "worker reload index duration",
   "type": "graph",
   "description": "gpu duration of reload shards",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_worker_gpu_operation_duration_sum{job=\"engine-tsfd-face-worker\",command=\"reload_shards\"}[1m]) / rate(search_worker_gpu_operation_duration_count{job=\"engine-tsfd-face-worker\",command=\"reload_shards\"}[1m])",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: GPU }"
    },
    {
     "expr": "search_worker_gpu_operation_duration{job=\"engine-tsfd-face-worker\",command=\"reload_shards\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: GPU, Quantile: {{ quantile }}}"
    },
    {
     "expr": "search_worker_cpu_operation_duration_sum{job=\"engine-tsfd-face-worker\",command=\"reload_shards\"} / search_worker_cpu_operation_duration_count{job=\"engine-tsfd-face-worker\",command=\"reload_shards\"}",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}, Device: CPU }"
    },
    {
     "expr": "search_worker_cpu_operation_duration{job=\"engine-tsfd-face-worker\",command=\"reload_shards\",quantile=\"0.9\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Device: CPU, Quantile: {{ quantile }}}"
    },
    {}
   ]
  },
  {
   "title": "other gpu duration",
   "type": "graph",
   "description": "gpu durarion of other operation",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_worker_gpu_operation_duration{job=\"engine-tsfd-face-worker\",command=\"recover_shard\"}",
     "legendFormat": "{Type: One, Pod: {{pod}}, Operation: recover_shard, Device: GPU, Operation: Recover, Quantile: {{ quantile }}}"
    },
    {
     "expr": "search_worker_cpu_operation_duration{job=\"engine-tsfd-face-worker\",command=\"recover_shard\"}",
     "legendFormat": "{Type: One, Pod: {{pod}}, Operation: recover_shard, Device: CPU, Operation: Recover, Quantile: {{ quantile }}}"
    }
   ]
  },
  {
   "title": "worker cassandra insert druation",
   "type": "graph",
   "description": "cassandra duration of add feature",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_worker_cassandra_operation_duration_sum{command='insert_feature',job=\"engine-tsfd-face-worker\"}[1m]) / rate(search_worker_cassandra_operation_duration_count{command='insert_feature',job=\"engine-tsfd-face-worker\"}[1m])",
     "legendFormat": "{Type: Avg, Pod: {{ pod }}}"
    },
    {
     "expr": "search_worker_cassandra_operation_duration{command='insert_feature',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: One, Pod: {{ pod }}, Quantile: {{ quantile }}}}"
    }
   ]
  },
  {
   "title": "other cassandra duration",
   "type": "graph",
   "description": "cassandra duration of other operation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_worker_cassandra_operation_duration{command='update_index',job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Type: One, Pod: {{pod}}, Operation: update_index, Quantile: {{ quantile }}}"
    }
   ]
  },
  { "title": "Oplog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Oplog produce count",
   "type": "graph",
   "description": "the num of oplog produced from tsfd(default)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oplog_add_feature_produce_count{job=\"engine-tsfd-face-worker\"})",
     "legendFormat": "{total, Operation: add_feature}"
    },
    {
     "expr": "oplog_add_feature_produce_count{job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Operation: add_feature, Pod: {{pod}}}"
    },
    {
     "expr": "sum(oplog_add_index_produce_count{job=\"engine-tsfd-face-worker\"})",
     "legendFormat": "{total, Operation: add_index}"
    },
    {
     "expr": "oplog_add_index_produce_count{job=\"engine-tsfd-face-worker\"}",
     "legendFormat": "{Operation: add_index, Pod: {{pod}}}"
    },
    {
     "expr": "sum(oplog_del_feature_produce_count{job=\"engine-tsfd-face-reducer\"})",
     "legendFormat": "{total, Operation: delete_index}"
    }
   ]
  }
 ]
}