{
 "title": "Engine / FaceVehicle-Image-Process-Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Sync FaceVehicle Processing Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(facevehicle_extract_processed{service=~\"engine-ips-worker-facevehicle-.*\"}[10m])) by (pod)"
    }
   ]
  },
  {
   "title": "Async FaceVehicle Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ips_photo_storage_succeed{service=~\"engine-ips-worker-facevehicle-.*\",stage=\"kafka\"}[10m])) by (pod, topic)"
    },
    {
     "expr": "sum(rate(ips_photo_storage_failed{service=~\"engine-ips-worker-facevehicle-.*\",stage=\"kafka\"}[10m])) by (pod, topic)"
    }
   ]
  },
  {
   "title": "Async FaceVehicle Input Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(capture_for_facevehicle_consume_count{service=~\"engine-ips-worker-facevehicle-.*\"}[10m])) by (tag)"
    }
   ]
  },
  {
   "title": "Sync FaceVehicle Processing Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(facevehicle_extract_failed{service=~\"engine-ips-worker-facevehicle-.*\"}[10m])) by (reason)"
    }
   ]
  },
  {
   "title": "Processors Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_processor_detail_duration{service=~\"engine-ips-worker-facevehicle-.*\"}) by (quantile, name)"
    }
   ]
  },
  {
   "title": "Face Vehicle Relate Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_facevehicle_relate_process_count{service=~\"engine-ips-worker-facevehicle-.*\"}[10m])) by (server, object, type)"
    }
   ]
  },
  {
   "title": "Async FaceVehicle Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(capture_for_facevehicle_process_duration{service=~\"engine-ips-worker-facevehicle-.*\"}) by (quantile, tag)"
    }
   ]
  }
 ]
}