{
 "title": "Engine / Face-Image-Process-Service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Sync Face Processing Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(face_extract_face_processed{service=~\"engine-ips-worker-face-.*-svc\"}[10m])) by (pod)"
    }
   ]
  },
  {
   "title": "Async Face Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ips_photo_storage_succeed{service=~\"engine-ips-worker-face-.*\",stage=\"kafka\"}[10m])) by (pod, topic)"
    },
    {
     "expr": "sum(rate(ips_photo_storage_failed{service=~\"engine-ips-worker-face-.*\",stage=\"kafka\"}[10m])) by (pod, topic)"
    }
   ]
  },
  {
   "title": "Async Face Processing Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_process_face_failed{service=~\"engine-ips-worker-face-.*\"}[10m])) by (reason)"
    }
   ]
  },
  {
   "title": "Sync Face Processing Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(face_extract_face_failed{service=~\"engine-ips-worker-face-.*\"}[10m])) by (reason)"
    }
   ]
  },
  {
   "title": "Async Face Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_process_face_process_duration{service=~\"engine-ips-worker-face-.*\"}) by (quantile, type)"
    }
   ]
  },
  {
   "title": "Sync Face Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(face_extract_process_duration{service=~\"engine-ips-worker-face-.*\"}) by (quantile, type)"
    }
   ]
  },
  {
   "title": "Processors Processing Duration In Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(image_processor_detail_duration{service=~\"engine-ips-worker-face-.*\"}) by (quantile, name)"
    }
   ]
  },
  {
   "title": "Face Detect Model Output Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_processor_detect_count{service=~\"engine-ips-worker-face-.*\"}[10m])) by (name, type)"
    }
   ]
  },
  {
   "title": "Face Image Decode Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_processor_decoder_count{service=~\"engine-ips-worker-face-.*\"}[10m])) by (name, state)"
    }
   ]
  }
 ]
}