{
 "title": "Infra / STPU Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "PU Usage",
   "type": "graph",
   "description": "stpu_requests_CONTAINER_POD_NODE",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"sensetime_com_stpu\"}",
     "legendFormat": "pu_requests_{{container}}_{{pod}}_{{node}}"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"sensetime_com_stpu\"}",
     "legendFormat": "pu_total_{{node}}"
    },
    {
     "expr": "-(sum(kube_pod_container_resource_requests{resource=\"sensetime_com_stpu\"}) by (node) - on (node) kube_node_status_allocatable{resource=\"sensetime_com_stpu\"})",
     "legendFormat": "pu_left_{{node}}"
    }
   ]
  },
  {
   "title": "PU Crop  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "stpu_pu_crop_util_percentage",
     "legendFormat": "pu_crop_util_{{instance}}_{{uuid}}"
    }
   ]
  },
  {
   "title": "PU ARM  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_arm_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "PU ARM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "stpu_pu_arm_mem", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "Chip CPU Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_chip_cpu_util", "legendFormat": "{{uuid}}_{{ instance }}" }
   ]
  },
  {
   "title": "PU Local Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "stpu_pu_local_mem", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "stpu_board_temperature",
     "legendFormat": "board_temp_{{instance}}-{{uuid}}"
    }
   ]
  },
  {
   "title": "PU ddr  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_ddr_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "Chip Top Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stpu_chip_top_mem", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "PU hist  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_hist_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "PU JPEG  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_jpeg_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "PU Resize  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_resize_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "PU TPU  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_tpu_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  },
  {
   "title": "PU VPU  Uitl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "stpu_pu_vpu_util_percentage", "legendFormat": "{{uuid}}_{{instance}}" }
   ]
  }
 ]
}