{
 "title": "Infra / Object Storage Gateway",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "nas 容量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_filesystem_size_bytes{mountpoint=~\".*nas.*\"}) by (device)",
     "legendFormat": "总量-{{device}}"
    },
    {
     "expr": "avg(node_filesystem_size_bytes{mountpoint=~\".*nas.*\"}) by (device) -  avg(node_filesystem_free_bytes{mountpoint=~\".*nas.*\"}) by (device)",
     "legendFormat": "已用-{{device}}"
    },
    {
     "expr": "avg(node_filesystem_free_bytes{mountpoint=~\".*nas.*\"}) by (device)",
     "legendFormat": "可用-{{device}}"
    }
   ]
  },
  { "title": "osg资源监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "osg memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"osg.*\", container!=\"POD\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"osg.*\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "network bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"osg.*\"}[1m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "osg 吞吐",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(osg_put_object_bytes[1m])) by (pod)",
     "legendFormat": "put:{{pod}}"
    },
    {
     "expr": "sum(rate(osg_get_object_bytes[1m])) by (pod)",
     "legendFormat": "get:{{pod}}"
    }
   ]
  },
  { "title": "osg API请求监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "put object /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(osg_put_object_requests[1m])) by (pod, grpc_code)"
    }
   ]
  },
  {
   "title": "平均put延时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(osg_put_object_latency_sum /osg_put_object_latency_count) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "get object/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(osg_get_object_requests[1m])) by (pod, grpc_code)"
    }
   ]
  },
  {
   "title": "平均get延时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(osg_get_object_latency_sum /osg_get_object_latency_count) by (pod)"
    }
   ]
  },
  {
   "title": "Grpc请求",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{service=\"osg-default\"} > 0"
    }
   ]
  },
  {
   "title": "Grpc处理延时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(grpc_server_handling_seconds_sum{service=\"osg-default\"} /grpc_server_handling_seconds_count{service=\"osg-default\"}) by (pod)"
    }
   ]
  },
  {
   "title": "osg图片压缩监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "已压缩Partition数量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(osg_compress_partition_count{bucket_name=~'.*_panoramic'}) by (bucket_name)"
      },
      {}
     ]
    },
    {
     "title": "解压缩请求速度",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(osg_compress_object_request{type=\"encode\"}[1m])) by (pod,type)"
      },
      {
       "expr": "sum(rate(osg_compress_object_request{type=\"decode\"}[1m])) by (pod,type)"
      }
     ]
    },
    {
     "title": "解压缩请求返回大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(osg_compress_object_bytes{type=\"encode\"}[1m])) by (pod,type)"
      },
      {
       "expr": "sum(rate(osg_compress_object_bytes{type=\"decode\"}[1m])) by (pod,type)"
      }
     ]
    }
   ]
  }
 ]
}