{
 "title": "Infra /  MLU Monitor",
 "description": "Data Center MLU Manager",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MLU 使用率",
   "type": "gauge",
   "description": "ai_board_utilization",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ai_board_utilization" }
   ]
  },
  {
   "title": "MLU 显存使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "ai_mem_utilization" }
   ]
  },
  {
   "title": "MLU 健康状态",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ai_board_health" }
   ]
  },
  {
   "title": "AiCore平均使用率",
   "type": "gauge",
   "description": "ai_core",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "avg(ai_core)" }
   ]
  },
  {
   "title": "MLU 平均温度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    { "expr": "avg(ai_temperature_celsius)" }
   ]
  },
  {
   "title": "MLU 功率",
   "type": "graph",
   "description": "ai_board_power",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ai_board_power",
     "legendFormat": "boardid: {{ boardid }}, model: {{ model }}, node: {{ nodeHostname }}, pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "MLU 使用率",
   "type": "graph",
   "description": "ai_board_utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ai_board_utilization",
     "legendFormat": "boardid: {{ boardid }}, model: {{ model }}, node: {{ nodeHostname }}, pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "MLU 显存使用率",
   "type": "graph",
   "description": "ai_mem_utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ai_mem_utilization",
     "legendFormat": "boardid: {{ boardid }}, model: {{ model }}, node: {{ nodeHostname }}, pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Ai Core 使用率",
   "type": "graph",
   "description": "ai_core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ai_core",
     "legendFormat": "ai_core: {{core}}, node: {{nodeHostname}},  instance: {{instance}}"
    }
   ]
  },
  {
   "title": "容器MLU显存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ai_container_resource_mlu_memory_utilization",
     "legendFormat": "container: {{ containerName }},  pod: {{ pod }}, node: {{ nodeHostname }}"
    }
   ]
  },
  {
   "title": "MLU 温度",
   "type": "graph",
   "description": "GPU Power Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ai_temperature_celsius",
     "legendFormat": "boardid: {{ boardid }}, coregroup: {{ coregroup }}, model: {{ model }}, node: {{ nodeHostname }}, pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "容器MLU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ai_container_resource_mlu_utilization",
     "legendFormat": "container: {{containerName}},  pod: {{ pod }}, node: {{nodeHostname}}"
    }
   ]
  }
 ]
}