{
 "title": "Infra / Cassandra",
 "tags": [ "component" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cassandra",
    "query": "label_values(jvm_memory_pool_bytes_used{job=~\"cassandra-.*\"}, job)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_memory_pool_bytes_used{job=\"$cassandra\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending Request",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{job=\"$cassandra\",threadpools=~\".*Native-Transport-Requests.*\"})"
    }
   ]
  },
  {
   "title": "Pending Mutation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{job=\"$cassandra\",threadpools=~\".*MutationStage.*\"})"
    }
   ]
  },
  {
   "title": "Pending Compaction",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_compaction_pendingtasks{job=\"$cassandra\"})"
    }
   ]
  },
  {
   "title": "Max Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(cassandra_clientrequest_latency_seconds{job=\"$cassandra\",clientrequest=~\".*Read.*\",quantile=\"0.999\"}) by (job)"
    }
   ]
  },
  {
   "title": "Max Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(cassandra_clientrequest_latency_seconds{job=\"$cassandra\",clientrequest=~\".*Write.*\",quantile=\"0.999\"}) by (job)"
    }
   ]
  },
  {
   "title": "Young GC",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{job=\"$cassandra\",gc=\"G1 Young Generation\"}[1m]))/sum(rate(jvm_gc_collection_seconds_count{job=\"$cassandra\",gc=\"G1 Young Generation\"}[1m]))"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",job=\"$cassandra\"}) / sum(jvm_memory_bytes_max{area=\"heap\", job=\"$cassandra\"})) * 100"
    }
   ]
  },
  {
   "title": "AVG CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (pod) ((irate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"$pod\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Timeout ClientRequest",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts_count{job=\"$cassandra\"} [1m]))"
    }
   ]
  },
  {
   "title": "Connection Timeout Counts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_connection_totaltimeouts_count{job=\"$cassandra\"} [1m]))"
    }
   ]
  },
  {
   "title": "Unavailable ClientRequest",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_unavailables_count{job=\"$cassandra\"}[1m])) "
    }
   ]
  },
  {
   "title": "Repaired Percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cassandra_table_percentrepaired{job=\"$cassandra\",keyspace!~\"system.*\", keyspace !~\"\", table!~\".*_by_.*\"})"
    }
   ]
  },
  {
   "title": "Max SStable Table",
   "type": "singlestat",
   "description": "当前sstable个数最多的表",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(cassandra_table_livesstablecount{job=\"$cassandra\",keyspace!~\"system.*\",keyspace!~\"\"}) by (keyspace, columnfamily))"
    }
   ]
  },
  {
   "title": "Snapshot Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_table_snapshotssize{job=\"$cassandra\",table!~\"\"})"
    }
   ]
  },
  {
   "title": "Disk Used All Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_totaldiskspaceused{job=\"$cassandra\"})"
    }
   ]
  },
  { "title": "System Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_network_receive_bytes_total{pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "$pod 内存分布及垃圾回收",
   "type": "graph",
   "description": "cached + jvm Eden + jvm Free + jvm Old\n一般cached数量稳定不变，查看Eden新生代jvm内存周期性变化即可看出jvm gc回收时间点，如果jvm free空间较大，可能需要调小jvm xmx内存",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "repeat": "pod",
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"$pod\"}) - sum by (pod) (label_replace(container_memory_usage_bytes{namespace=\"component\",pod=~\"$pod\",container!=\"POD\"},\"pod\",\"$1\",\"pod\",\"(.*)\"))",
     "legendFormat": "{{pod}}-pod-free"
    },
    {
     "expr": "sum by (pod) (label_replace(container_memory_usage_bytes{namespace=\"component\",pod=~\"$pod\",container!=\"POD\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) - sum by (pod) (jvm_memory_bytes_max{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-page-cached"
    },
    {
     "expr": "sum by (pod) (jvm_memory_bytes_max{pod=~\"$pod\"}) - sum by (pod) (jvm_memory_bytes_used{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-jvm-free"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",pool=\"G1 Old Gen\"}",
     "legendFormat": "{{pod}}-jvm-Old"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",pool=\"G1 Eden Space\"}",
     "legendFormat": "{{pod}}-jvm-Eden"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pod=~\"$pod\",pool!~\"G1 Eden Space|G1 Old Gen\"})",
     "legendFormat": "{{pod}}-jvm-other"
    }
   ]
  },
  {
   "title": "$pod  IOPS",
   "type": "graph",
   "description": "每秒读写硬盘数量，当前只针对foundry F1-8机型计算，其他机型计算不正确，会额外计入其他硬盘，SAS 盘iops是4块盘sum之后的结果，也有些超过理论值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "repeat": "pod",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=~\"/dev/sdb|/dev/sdc|/dev/sdd|/dev/sde\"}[1m])) > 1",
     "legendFormat": "sas_write_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_reads_total{pod=~\"$pod\",device=~\"/dev/sdb|/dev/sdc|/dev/sdd|/dev/sde\"}[1m])) > 1",
     "legendFormat": "sas_read_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=\"/dev/sdj\"}[1m])) > 1",
     "legendFormat": "ssd_write_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=\"/dev/sdj\"}[1m])) > 1",
     "legendFormat": "ssd_read_{{device}}_{{pod}}"
    }
   ]
  },
  {
   "title": "$pod 内存分布及垃圾回收",
   "type": "graph",
   "description": "cached + jvm Eden + jvm Free + jvm Old\n一般cached数量稳定不变，查看Eden新生代jvm内存周期性变化即可看出jvm gc回收时间点，如果jvm free空间较大，可能需要调小jvm xmx内存",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"$pod\"}) - sum by (pod) (label_replace(container_memory_usage_bytes{namespace=\"component\",pod=~\"$pod\",container!=\"POD\"},\"pod\",\"$1\",\"pod\",\"(.*)\"))",
     "legendFormat": "{{pod}}-pod-free"
    },
    {
     "expr": "sum by (pod) (label_replace(container_memory_usage_bytes{namespace=\"component\",pod=~\"$pod\",container!=\"POD\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) - sum by (pod) (jvm_memory_bytes_max{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-page-cached"
    },
    {
     "expr": "sum by (pod) (jvm_memory_bytes_max{pod=~\"$pod\"}) - sum by (pod) (jvm_memory_bytes_used{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-jvm-free"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",pool=\"G1 Old Gen\"}",
     "legendFormat": "{{pod}}-jvm-Old"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",pool=\"G1 Eden Space\"}",
     "legendFormat": "{{pod}}-jvm-Eden"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pod=~\"$pod\",pool!~\"G1 Eden Space|G1 Old Gen\"})",
     "legendFormat": "{{pod}}-jvm-other"
    }
   ]
  },
  {
   "title": "$pod  IOPS",
   "type": "graph",
   "description": "每秒读写硬盘数量，当前只针对foundry F1-8机型计算，其他机型计算不正确，会额外计入其他硬盘，SAS 盘iops是4块盘sum之后的结果，也有些超过理论值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=~\"/dev/sdb|/dev/sdc|/dev/sdd|/dev/sde\"}[1m])) > 1",
     "legendFormat": "sas_write_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_reads_total{pod=~\"$pod\",device=~\"/dev/sdb|/dev/sdc|/dev/sdd|/dev/sde\"}[1m])) > 1",
     "legendFormat": "sas_read_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=\"/dev/sdj\"}[1m])) > 1",
     "legendFormat": "ssd_write_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=\"/dev/sdj\"}[1m])) > 1",
     "legendFormat": "ssd_read_{{device}}_{{pod}}"
    }
   ]
  },
  {
   "title": "$pod 内存分布及垃圾回收",
   "type": "graph",
   "description": "cached + jvm Eden + jvm Free + jvm Old\n一般cached数量稳定不变，查看Eden新生代jvm内存周期性变化即可看出jvm gc回收时间点，如果jvm free空间较大，可能需要调小jvm xmx内存",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"$pod\"}) - sum by (pod) (label_replace(container_memory_usage_bytes{namespace=\"component\",pod=~\"$pod\",container!=\"POD\"},\"pod\",\"$1\",\"pod\",\"(.*)\"))",
     "legendFormat": "{{pod}}-pod-free"
    },
    {
     "expr": "sum by (pod) (label_replace(container_memory_usage_bytes{namespace=\"component\",pod=~\"$pod\",container!=\"POD\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) - sum by (pod) (jvm_memory_bytes_max{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-page-cached"
    },
    {
     "expr": "sum by (pod) (jvm_memory_bytes_max{pod=~\"$pod\"}) - sum by (pod) (jvm_memory_bytes_used{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-jvm-free"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",pool=\"G1 Old Gen\"}",
     "legendFormat": "{{pod}}-jvm-Old"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",pool=\"G1 Eden Space\"}",
     "legendFormat": "{{pod}}-jvm-Eden"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pod=~\"$pod\",pool!~\"G1 Eden Space|G1 Old Gen\"})",
     "legendFormat": "{{pod}}-jvm-other"
    }
   ]
  },
  {
   "title": "$pod  IOPS",
   "type": "graph",
   "description": "每秒读写硬盘数量，当前只针对foundry F1-8机型计算，其他机型计算不正确，会额外计入其他硬盘，SAS 盘iops是4块盘sum之后的结果，也有些超过理论值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=~\"/dev/sdb|/dev/sdc|/dev/sdd|/dev/sde\"}[1m])) > 1",
     "legendFormat": "sas_write_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_reads_total{pod=~\"$pod\",device=~\"/dev/sdb|/dev/sdc|/dev/sdd|/dev/sde\"}[1m])) > 1",
     "legendFormat": "sas_read_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=\"/dev/sdj\"}[1m])) > 1",
     "legendFormat": "ssd_write_{{device}}_{{pod}}"
    },
    {
     "expr": "sum by (pod)(irate(container_fs_writes_total{pod=~\"$pod\",device=\"/dev/sdj\"}[1m])) > 1",
     "legendFormat": "ssd_read_{{device}}_{{pod}}"
    }
   ]
  },
  { "title": "Request error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Exception & unavaliable & Timeout",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1,sum(rate(cassandra_clientrequest_unavailables_count{job=\"$cassandra\"}[1m])) by (clientrequest))",
     "legendFormat": "unavailables-{{clientrequest}}"
    },
    {
     "expr": "sum(rate(cassandra_connection_totaltimeouts_count{job=\"$cassandra\"}[1m]))",
     "legendFormat": "timeouts-{{clientrequest}}"
    },
    {
     "expr": "sum(rate(cassandra_clientrequest_totaltimeouts{job=\"$cassandra\"}[1m])) by (clientrequest)",
     "legendFormat": "totaltimeouts-{{clientrequest}}"
    },
    {
     "expr": "rate(cassandra_storage_exceptions{job=\"$cassandra\"}[1m])",
     "legendFormat": "exceptions-{{pod}}"
    }
   ]
  },
  {
   "title": "speculative retries",
   "type": "graph",
   "description": "创建表时定义，默认speculative_retry=99PERCENTILE 表示coordiantor 等待当前请求返回时间超过99% 平均返回时间后，尝试发送请求到其他节点，避免因为当前节点负载高或正在gc等原因一致等待返回，提高响应时间，此metric表示当前有多少请求是retry返回的，表明某些节点响应较慢",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cassandra_columnfamily_speculativeretries{job=\"cassandra-default\",keyspace!~\"system.*\",columnfamily!~\"schema_migrations\",columnfamily!~\"\"}[1m])) by (keyspace, columnfamily)"
    }
   ]
  },
  { "title": "Client Request & Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Client Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(1, avg(cassandra_clientrequest_latency_seconds{job=\"$cassandra\",clientrequest=~\".*Read.*\",quantile=\"0.999\"}) by (clientrequest))",
     "legendFormat": "{{clientrequest}}"
    },
    {
     "expr": "topk(1,avg(cassandra_clientrequest_latency_seconds{job=\"$cassandra\",clientrequest=~\".*Write.*\",quantile=\"0.999\"}) by (clientrequest))",
     "legendFormat": "{{clientrequest}}"
    }
   ]
  },
  {
   "title": "Coordinator Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(cassandra_table_coordinatorreadlatency_seconds{job=\"$cassandra\",quantile=\"0.999\",keyspace!~\"system.*\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}} - {{table}}"
    }
   ]
  },
  {
   "title": "Current Connection Timeout",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Current" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_connection_timeouts_count{job=\"$cassandra\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Auth & Connected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_client_connectednativeclients{job=\"$cassandra\"})",
     "legendFormat": "connectd native clients"
    },
    {
     "expr": "sum(rate(cassandra_client_authsuccess{job=\"$cassandra\"}[1m])) ",
     "legendFormat": "auth success"
    },
    {
     "expr": "sum(rate(cassandra_client_authfailure{job=\"$cassandra\"}[1m])) ",
     "legendFormat": "auth failed"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "pending && active tasks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none", "label": "Pending" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_threadpools_pendingtasks{service=\"$cassandra\"}) by (threadpools)",
       "legendFormat": "pending-{{path}}-{{threadpools}}"
      },
      {
       "expr": "sum(cassandra_threadpools_activetasks{service=\"$cassandra\"}) by (threadpools)",
       "legendFormat": "active-{{path}}-{{threadpools}}"
      }
     ]
    },
    {
     "title": "block task",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "none", "label": "Current BlocK" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_threadpools_totalblockedtasks{service=\"$cassandra\"}[1m])) by (threadpools)",
       "legendFormat": "totalblock-{{threadpools}}"
      },
      {
       "expr": "sum(rate(cassandra_threadpools_currentlyblockedtasks{service=\"$cassandra\"}[1m])) by (threadpools)",
       "legendFormat": "currentblock-{{threadpools}}"
      }
     ]
    },
    {
     "title": "Completed Tasks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_threadpools_completedtasks{job=\"$cassandra\"}[1m])) by (path, threadpools)"
      }
     ]
    }
   ]
  },
  {
   "title": "Hinted Handoff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write/Sec & send current",
     "type": "graph",
     "description": "wps表示每秒写入节点的hints数量\nSendFrom表示从节点瞬时发送到hints对应目标节点的hints数量，即之前某些节点无响应积累一些hints文件，待目标节点恢复后一起发送",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "wps", "label": "Write/ Sec" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_storage_totalhints{job=\"$cassandra\"}[1m])",
       "legendFormat": "Write-{{pod}}-{{instance}}"
      },
      {
       "expr": "cassandra_storage_totalhintsinprogress{job=\"$cassandra\"}",
       "legendFormat": "SendFrom-{{pod}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Hints Failed & Successed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Failed & TimeOut" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_hintsservice_hintsfailed{job=\"$cassandra\"}[1m])",
       "legendFormat": "failed-{{pod}}-{{instance}}"
      },
      {
       "expr": "rate(cassandra_hintsservice_hintstimedout{job=\"$cassandra\"}[1m])",
       "legendFormat": "timeout-{{pod}}-{{instance}}"
      },
      {
       "expr": "rate(cassandra_hintsservice_hintssucceeded{job=\"$cassandra\"}[1m])",
       "legendFormat": "succeeded-{{pod}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "Total Compaction" }
     ],
     "targets": [
      {
       "expr": "cassandra_compaction_totalcompactionscompleted{job=\"$cassandra\"}",
       "legendFormat": "total-{{pod}}-{{instance}}"
      },
      {
       "expr": "cassandra_compaction_pendingtasks{job=\"$cassandra\"}",
       "legendFormat": "pending-{{pod}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Compaction Per Table",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes", "label": "Compaction Written" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_columnfamily_pendingcompactions{keyspace!~\"system.*\",keyspace!~\"\"}) by (keyspace, columnfamily)",
       "legendFormat": "pendingCompactions-{{keyspace}}-{{columnfamily}}"
      },
      {
       "expr": "sum(rate(cassandra_columnfamily_compactionbyteswritten{keyspace!~\"system.*\",keyspace!~\"\"}[1m])) by (keyspace, columnfamily)",
       "legendFormat": "compactionBytesWritten-{{keyspace}}-{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Total Compaction Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes", "label": "Compaction Written" }
     ],
     "targets": [
      {
       "expr": "cassandra_compaction_bytescompacted{job=\"$cassandra\"}",
       "legendFormat": "compactionBytes-{{pod}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Read Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Materialized View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_latency{job=\"$cassandra\",clientrequest=~\"ViewWrite\"}[1m])",
       "legendFormat": "{{pod}} {{clientrequest}}"
      }
     ]
    },
    {
     "title": "Write Form Base Table To View With CL.One",
     "type": "graph",
     "description": "Time between when mutation is applied to base table and when CL.ONE is achieved on view.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_viewwritelatency{job=\"$cassandra\",clientrequest=~\"ViewWrite\"}[1m])",
       "legendFormat": "{{pod}} {{clientrequest}}"
      }
     ]
    },
    {
     "title": "Local Read Time When Update",
     "type": "graph",
     "description": "Time taken during the local read of a materialized view update.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_keyspace_viewreadtime{job=\"$cassandra\",keyspace!~\"system.*\"}[1m])",
       "legendFormat": "{{pod}}-{{keyspace}}"
      }
     ]
    },
    {
     "title": "Partition Lock Time When MV Update",
     "type": "graph",
     "description": "Time taken acquiring a partition lock for materialized view updates on this table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_keyspace_viewlockacquiretime{job=\"$cassandra\",keyspace!~\"system.*\"}[1m])",
       "legendFormat": "{{pod}}-{{keyspace}}"
      }
     ]
    },
    {
     "title": "MV Writes Tasks Status",
     "type": "graph",
     "description": "Total number of attempted view replica writes.\nTotal number of succeded view replica writes.\nViewReplicasAttempted - ViewReplicasSuccess.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "Attemped && Success" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_viewreplicasattempted{job=\"$cassandra\",keyspace!~\"system.*\"}[1m])",
       "legendFormat": "attempted-{{pod}}"
      },
      {
       "expr": "rate(cassandra_clientrequest_viewreplicassuccess{job=\"$cassandra\",keyspace!~\"system.*\"}[1m])",
       "legendFormat": "success-{{pod}}"
      },
      {
       "expr": "rate(cassandra_clientrequest_viewpendingmutations{job=\"$cassandra\",keyspace!~\"system.*\"}[1m])",
       "legendFormat": "pending-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Commitlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed Tasks & Writed  Size  / Sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none", "label": "Complete Tasks / Sec" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_commitlog_completedtasks{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "completed_tasks-{{pod}}"
      },
      {
       "expr": "rate(cassandra_commitlog_totalcommitlogsize{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "commitlog_size-{{pod}}"
      }
     ]
    },
    {
     "title": "Pending Tasks & Waiting  Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_commitlog_pendingtasks{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "{{pod}} Pending tasks"
      },
      {
       "expr": "rate(cassandra_commitlog_waitingoncommit{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "{{pod}} Waiting Fsync"
      },
      {
       "expr": "rate(cassandra_commitlog_waitingonsegmentallocation{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "{{pod}} Waiting Allocation"
      }
     ]
    }
   ]
  },
  {
   "title": "Communication Message",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Small Message Task",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none", "label": "Completed" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_connection_smallmessagecompletedtasks{job=\"$cassandra\"}[1m])) by (pod)",
       "legendFormat": "completed-{{address}}-{{instance}}-{{pod}}"
      },
      {
       "expr": "sum(rate(cassandra_connection_smallmessagedroppedtasks{job=\"$cassandra\"}[1m])) by (pod) ",
       "legendFormat": "dropped-{{address}}-{{instance}}-{{pod}}"
      },
      {
       "expr": "sum(rate(cassandra_connection_smallmessagependingtasks{job=\"$cassandra\"}[1m])) by (pod)",
       "legendFormat": "pending-{{address}}-{{instance}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Large Message Task",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Completed" }
     ],
     "targets": [
      {
       "expr": "cassandra_connection_largemessagecompletedtasks{job=\"$cassandra\"}",
       "legendFormat": "completed-{{address}}-{{instance}}-{{pod}}"
      },
      {
       "expr": "cassandra_connection_largemessagedroppedtasks{job=\"$cassandra\"}",
       "legendFormat": "dropped-{{address}}-{{instance}}-{{pod}}"
      },
      {
       "expr": "cassandra_connection_largemessagependingtasks{job=\"$cassandra\"}",
       "legendFormat": "pending-{{address}}-{{instance}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Gossip Message Task",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Completed" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_connection_gossipmessagecompletedtasks{job=\"$cassandra\"}[1m])) by (pod)",
       "legendFormat": "completed-{{address}}-{{instance}}-{{pod}}"
      },
      {
       "expr": "sum(rate(cassandra_connection_gossipmessagedroppedtasks{job=\"$cassandra\"}[1m])) by (pod)",
       "legendFormat": "dropped-{{address}}-{{instance}}-{{pod}}"
      },
      {
       "expr": "sum(rate(cassandra_connection_gossipmessagependingtasks{job=\"$cassandra\"}[1m])) by (pod)",
       "legendFormat": "pending-{{address}}-{{instance}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memtable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes", "label": "Total Data" }
     ],
     "targets": [
      {
       "expr": "(avg(cassandra_columnfamily_memtableonheapsize{job=\"$cassandra\",keyspace!~\"system.*\",columnfamily!~\"\"}) by (keyspace,columnfamily)) + (avg(cassandra_columnfamily_memtableoffheapsize{job=\"$cassandra\",keyspace!~\"system.*\",columnfamily!~\"\"}) by (keyspace,columnfamily))",
       "legendFormat": "{{keyspace}}-{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Live Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes", "label": "Live Data" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_columnfamily_memtablelivedatasize{job=\"$cassandra\",keyspace!~\"system.*\",columnfamily!~\"\"}) by (keyspace,columnfamily)",
       "legendFormat": "live-{{keyspace}}-{{columnfamily}}"
      }
     ]
    },
    {
     "title": "flush Times When memtable switched out",
     "type": "graph",
     "description": "Number of times flush has resulted in the memtable being switched out.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_columnfamily_memtableswitchcount{job=\"$cassandra\",keyspace!~\"system.*\",columnfamily!~\"\"}[1m])) by (pod,keyspace, columnfamily)",
       "legendFormat": "{{pod}}-{{keyspace}}-{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Columns Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_columnfamily_memtablecolumnscount{job=\"$cassandra\",keyspace!~\"system.*\",columnfamily!~\"\"}) by (pod,keyspace,columnfamily)"
      }
     ]
    }
   ]
  },
  {
   "title": "SStable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "sstable counts by  table",
     "type": "graph",
     "description": "Count-xxx-xxx  每个表当前的sstable数量",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "none", "label": "sstable  per  table" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_columnfamily_livesstablecount{job=\"cassandra-default\",keyspace!~\"system.*\",keyspace!~\"\"}) by (keyspace, columnfamily) > 0",
       "legendFormat": "Counts-{{keyspace}}.{{columnfamily}}"
      }
     ]
    },
    {
     "title": "sstable counts by read",
     "type": "graph",
     "description": "CountPerRead-xxx-xxx 每次读访问的sstable",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "none", "label": "sstable per Read" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_columnfamily_sstablesperreadhistogram{job=\"cassandra-default\",keyspace!~\"system.*\",keyspace!~\"\"}[1m])) by (keyspace, columnfamily) > 0",
       "legendFormat": "CountsPerRead-{{keyspace}}.{{columnfamily}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes", "label": "Pod Disk Used" }
     ],
     "targets": [
      {
       "expr": "cassandra_storage_load{job=\"$cassandra\"} > 0",
       "legendFormat": "pod-{{pod}}"
      },
      {
       "expr": "avg(cassandra_columnfamily_totaldiskspaceused{job=\"$cassandra\",keyspace!~\"system.*\",keyspace!~\"\"}) by (keyspace,columnfamily)  > 0",
       "legendFormat": "table-{{keyspace}}.{{columnfamily}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repair",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Repair",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short", "label": "attempted" }
     ],
     "targets": [
      {
       "expr": "cassandra_readrepair_attempted{job=\"$cassandra\"}",
       "legendFormat": "attempted-{{pod}}"
      },
      {
       "expr": "cassandra_readrepair_repairedbackground{job=\"$cassandra\"}",
       "legendFormat": "background-{{pod}}"
      },
      {
       "expr": "cassandra_readrepair_repairedblocking{job=\"$cassandra\"}",
       "legendFormat": "blocking-{{pod}}"
      }
     ]
    },
    {
     "title": "Read Repair Request By Table",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_readrepairrequests{job=\"$cassandra\",keyspace!~\"system.*\",keyspace!~\"\"}",
       "legendFormat": "requests-{{keyspace}}.{{table}}"
      }
     ]
    },
    {
     "title": "Repaired Percent By Table",
     "type": "graph",
     "description": "表的修复比例",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percent", "label": "repaired percent" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_table_percentrepaired{job=\"$cassandra\",keyspace!~\"system.*\",keyspace!~\"\",table!~\".*_by_.*\"}) by (keyspace, table)",
       "legendFormat": "percent-repaired-{{keyspace}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KeyCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entries Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none", "label": "Entries Count" }
     ],
     "targets": [
      {
       "expr": "cassandra_cache_entries{job=\"cassandra-default\",cache=\"KeyCache\"}",
       "legendFormat": "entries-{{pod}}-{{cache}}"
      }
     ]
    },
    {
     "title": "Entries Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "bytes", "label": "Cache Size" }
     ],
     "targets": [
      {
       "expr": "cassandra_cache_size{job=\"cassandra-default\",cache=\"KeyCache\"}",
       "legendFormat": "size-{{pod}}-{{cache}}"
      }
     ]
    },
    {
     "title": "Entries  HitRate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percentunit", "label": "HitRate" }
     ],
     "targets": [
      {
       "expr": "cassandra_cache_hitrate{job=\"cassandra-default\",cache=\"KeyCache\"}",
       "legendFormat": "hitrate-{{pod}}-{{cache}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod Stream Between Pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "repeat": "pod",
     "yaxes": [
      { "format": "bytes", "label": "Pod Streaming" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_streaming_incomingbytes{job=\"$cassandra\",pod=\"$pod\"}[1m])",
       "legendFormat": "{{address}}=>{{instance}}-{{pod}}"
      }
     ]
    },
    {
     "title": "$pod Stream Between Pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes", "label": "Pod Streaming" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_streaming_incomingbytes{job=\"$cassandra\",pod=\"$pod\"}[1m])",
       "legendFormat": "{{address}}=>{{instance}}-{{pod}}"
      }
     ]
    },
    {
     "title": "$pod Stream Between Pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes", "label": "Pod Streaming" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_streaming_incomingbytes{job=\"$cassandra\",pod=\"$pod\"}[1m])",
       "legendFormat": "{{address}}=>{{instance}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Total Streaming",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "bytes", "label": "Pod Streaming" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_streaming_totalincomingbytes{job=\"$cassandra\"}[1m])",
       "legendFormat": "incoming-{{pod}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloom Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "false positives & ratio",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Positives" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_columnfamily_bloomfilterfalsepositives{job=\"$cassandra\", keyspace!~\"system.*\",columnfamily!=\"\"}) by (keyspace, columnfamily)",
       "legendFormat": "false positives {{keyspace}}.{{columnfamily}}"
      },
      {
       "expr": "avg(cassandra_columnfamily_bloomfilterfalseratio{job=\"$cassandra\", keyspace!~\"system.*\",columnfamily!=\"\"}) by (keyspace, columnfamily)",
       "legendFormat": "false ratio {{keyspace}}.{{columnfamily}}"
      }
     ]
    },
    {
     "title": "disk & memory used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "bytes", "label": "Disk" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_columnfamily_bloomfilterdiskspaceused{job=\"$cassandra\", keyspace!~\"system.*\",columnfamily!=\"\"}) by (keyspace, columnfamily)",
       "legendFormat": "disk {{keyspace}}.{{columnfamily}}"
      },
      {
       "expr": "sum(cassandra_columnfamily_bloomfilteroffheapmemoryused{job=\"$cassandra\", keyspace!~\"system.*\",columnfamily!=\"\"}) by (keyspace, columnfamily)",
       "legendFormat": "memory {{keyspace}}.{{columnfamily}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$cassandra\",gc=\"G1 Old Generation\"}[3m])/rate(jvm_gc_collection_seconds_count{job=\"$cassandra\",gc=\"G1 Old Generation\"}[3m])",
       "legendFormat": "{{pod}}-old-Gen"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$cassandra\",gc=\"G1 Young Generation\"}[3m])/rate(jvm_gc_collection_seconds_count{job=\"$cassandra\",gc=\"G1 Young Generation\"}[3m])",
       "legendFormat": "{{pod}}-Young-Gen"
      }
     ]
    },
    {
     "title": "GC Count / Sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$cassandra\",gc=\"G1 Old Generation\"}[3m])",
       "legendFormat": "{{pod}}-old"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$cassandra\",gc=\"G1 Young Generation\"}[3m])",
       "legendFormat": "{{pod}}-Young"
      }
     ]
    },
    {
     "title": "JVM Non-Heap Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_bytes_used{area=\"nonheap\",job=\"$cassandra\"})",
       "legendFormat": "heap-used"
      },
      {
       "expr": "avg(jvm_memory_bytes_committed{area=\"nonheap\",job=\"$cassandra\"})",
       "legendFormat": "heap-capacity"
      }
     ]
    },
    {
     "title": "JVM Heap Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_bytes_used{area=\"heap\",job=\"$cassandra\"})",
       "legendFormat": "{{pod}}-heap-used"
      },
      {
       "expr": "avg(jvm_memory_bytes_max{area=\"heap\",job=\"$cassandra\"})",
       "legendFormat": "{{pod}}-heap-capacity"
      }
     ]
    },
    {
     "title": "Threads Counts",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$cassandra\"}"
      }
     ]
    },
    {
     "title": "JVM Pool Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_pool_bytes_used{job=\"$cassandra\"})",
       "legendFormat": "pool-used"
      },
      {
       "expr": "avg(jvm_memory_pool_bytes_max{job=\"$cassandra\"})",
       "legendFormat": "pool-capacity"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"$cassandra\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "CQLprepared ratio",
     "type": "graph",
     "description": "prepared cql占所有cql比例",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_cql_preparedstatementsratio{job=\"$cassandra\"}",
       "legendFormat": "ratio-{{pod}}"
      }
     ]
    },
    {
     "title": "CQL statements/ sec & prepared ratio",
     "type": "graph",
     "description": "平均每秒执行的cql数，及prepared cql占所有cql比例",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cql_regularstatementsexecuted{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "regular-{{pod}}"
      },
      {
       "expr": "rate(cassandra_cql_preparedstatementsexecuted{job=\"$cassandra\"}[1m]) > 0",
       "legendFormat": "prepared-{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}