{
 "title": "Infra / Atlas 310p / NPU Monitor",
 "description": "Data Center GPU Manager",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"npu-exporter.*\"}, node)"
    }
   },
   {
    "name": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"npu-exporter.*\",node=\"$node\"}, pod_ip)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(npu_chip_info_health_status{instance =~\"$pod_ip.*\"}, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Atlas 加速卡总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_npu_nums{instance=~\"$pod_ip.*\"}"
    }
   ]
  },
  {
   "title": "加速卡状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_health_status{instance=~\"$pod_ip.*\", id=~\"$id\"}",
     "legendFormat": "id: {{id}}"
    }
   ]
  },
  {
   "title": "单个显卡最大显存总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(npu_chip_info_total_memory{instance=~\"$pod_ip.*\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "NPU显存平均使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(npu_chip_info_used_memory{instance=~\"$pod_ip.*\", id=~\"$id\"} / npu_chip_info_total_memory{instance=~\"$pod_ip.*\", id=~\"$id\"} * 100)"
    }
   ]
  },
  {
   "title": "NPU平均温度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(npu_chip_info_temperature{instance=~\"$pod_ip.*\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "NPU平均功率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " avg(npu_chip_info_power{instance=~\"$pod_ip.*\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "npu 版本",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_name{instance=~\"$pod_ip.*\", id=~\"$id\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "npu错误码",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(npu_chip_info_error_code{instance=~\"$pod_ip.*\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "NPU 显存使用",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_used_memory{instance=~\"$pod_ip.*\", id=~\"$id\"}",
     "legendFormat": "{{instance}} id: {{id}}"
    }
   ]
  },
  {
   "title": "NPU 温度",
   "type": "graph",
   "description": "GPU Power Usage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_temperature{instance=~\"$pod_ip.*\", id=~\"$id\"}",
     "legendFormat": "{{instance}} id: {{id}}"
    }
   ]
  },
  {
   "title": "NPU 功率",
   "type": "graph",
   "description": "npu_power",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_power{instance=~\"$pod_ip.*\", id=~\"$id\"}",
     "legendFormat": "{{instance}} id: {{id}}"
    }
   ]
  },
  {
   "title": "Ai Core 使用率",
   "type": "graph",
   "description": "npu_aicore_util_percentage",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_utilization{instance=~\"$pod_ip.*\", id=~\"$id\"}",
     "legendFormat": "{{instance}} id: {{id}}"
    }
   ]
  }
 ]
}