{
 "title": "Infra / Clustering-Job-Manager",
 "description": "Statistics of clustering job manager",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "classification job statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clustering_job_manager_counter_statistics{job_name=\"classification_job\"}[1h])"
    }
   ]
  },
  {
   "title": "clustering job statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clustering_job_manager_counter_statistics{job_name=\"clustering_job\"}[1h])"
    }
   ]
  },
  {
   "title": "labeling job statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clustering_job_manager_counter_statistics{job_name=\"labeling_job\"}[1d])"
    }
   ]
  },
  {
   "title": "train index job statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clustering_job_manager_gauge_statistics{job_name=\"train_index_job\"}"
    }
   ]
  }
 ]
}