{
 "title": "Infra / GPU Monitor",
 "description": "Data Center GPU Manager",
 "tags": [ "GPU" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{node=~\".*\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU平均温度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  },
  {
   "title": "GPU总功率",
   "type": "gauge",
   "description": "GPU Power Total",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_POWER_USAGE)" }
   ]
  },
  {
   "title": "GPU 温度",
   "type": "graph",
   "description": "GPU Power Usage",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{node=\"$node\"}",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 使用率",
   "type": "graph",
   "description": "GPU utilization last 5m (in %)",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{node=\"$node\"}",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "显存使用率",
   "type": "graph",
   "description": "Framebuffer memory used (in MiB).",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(DCGM_FI_DEV_FB_USED{node=\"$node\"}) by (gpu, node) / (sum(DCGM_FI_DEV_FB_USED{node=\"$node\"}) by (gpu, node) + sum(DCGM_FI_DEV_FB_FREE{node=\"$node\"}) by (gpu, node))",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU内存时钟",
   "type": "graph",
   "description": "GPU Memory Clocks",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{node=\"$node\"}",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM 时钟",
   "type": "graph",
   "description": "GPU SM Clock",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{node=\"$node\"}",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "PCIe接收速率(KB/s)",
   "type": "graph",
   "description": "Total number of bytes received through PCIe RX rate (in KB/s) via NVML.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_PCIE_RX_THROUGHPUT{node=\"$node\"}[5m])",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "PCIe发送速率(KB/s)",
   "type": "graph",
   "description": "Total number of bytes transmitted through PCIe TX rate (in KB/s) via NVML.",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_PCIE_TX_THROUGHPUT{gpu=~\"[0-9]*\",node=\"$node\"}[5m])",
     "legendFormat": "Node {{node}} GPU {{gpu}}"
    }
   ]
  }
 ]
}