{
 "title": "MinIO Overview",
 "description": "MinIO dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "MinIO Host",
    "query": "label_values(minio_version_info,instance)"
   },
   {
    "name": "disk",
    "label": "Drive",
    "query": "label_values(disk_storage_total,disk)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time() - max(process_start_time_seconds{instance=~\"$instance\"})) / 86400",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Online disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minio_disks_total)",
     "legendFormat": "Total online disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(bucket_usage_size) by (instance))"
    }
   ]
  },
  {
   "title": "Data Growth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(bucket_usage_size) by (instance))",
     "legendFormat": "Total Storage Used"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (object_size) (bucket_objects_histogram)",
     "legendFormat": "{{object_size}}"
    }
   ]
  },
  {
   "title": "Total Offline disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_offline)",
     "legendFormat": "Total offline disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (instances) (minio_version_info)"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (s3_rx_bytes_total)"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bucket) (bucket_objects_count))"
    }
   ]
  },
  {
   "title": "S3 API Request & Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum without (instance,api)(rate(s3_requests_total[10m]))",
     "legendFormat": "S3 Requests"
    },
    {
     "expr": "sum without (instance,api)(rate(s3_errors_total[10m]))",
     "legendFormat": "S3 Errors"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (instance)(process_open_fds)"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (instance)(s3_tx_bytes_total)"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(bucket_objects_count) by (instance))"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (go_goroutines)"
    }
   ]
  },
  {
   "title": "S3 API Data Transfer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum without (instance,api)(rate(s3_tx_bytes_total[5m]))",
     "legendFormat": "S3 Data Sent"
    },
    {
     "expr": "sum without (instance,api)(rate(s3_rx_bytes_total[5m]))",
     "legendFormat": "S3 Data Received"
    }
   ]
  },
  { "title": "API ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total S3 API Data Transfer",
   "type": "graph",
   "description": "Total number of s3 bytes received and sent per MinIO server instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (s3_rx_bytes_total)",
     "legendFormat": "S3 Bytes Received {{instance}}"
    },
    {
     "expr": "sum without (instance) (s3_tx_bytes_total)",
     "legendFormat": "S3 Bytes Sent {{instance}}"
    }
   ]
  },
  {
   "title": "Active S3 Requests",
   "type": "graph",
   "description": "Total number of active s3 requests in current MinIO instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(s3_requests_current[5m])",
     "legendFormat": "Instance {{instance}} function {{api}}"
    }
   ]
  },
  {
   "title": "Internode Data Transfer",
   "type": "graph",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "internode_rx_bytes_total",
     "legendFormat": "Internode Bytes Received {{instance}}"
    },
    {
     "expr": "internode_tx_bytes_total",
     "legendFormat": "Internode Bytes Sent {{instance}}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Online Disks",
   "type": "graph",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_disks_total - minio_disks_offline",
     "legendFormat": "Online Disks {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Disk capacity used per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_used",
     "legendFormat": "Used Capacity {{instance}} {{disk}}"
    }
   ]
  }
 ]
}