{
 "title": "Infra / Kafka Topics",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_burrow_topic_partition_offset, service)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kafka_burrow_topic_partition_offset{service=\"$instance\"},cluster)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_burrow_topic_partition_offset{service=\"$instance\",cluster=\"$cluster\"},topic)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{topic='$topic'},group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_burrow_topic_partition_offset{service='$instance',cluster='$cluster',topic='$topic'})",
     "legendFormat": "$topic"
    }
   ]
  },
  {
   "title": "Write records per seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_burrow_topic_partition_offset{service='$instance',cluster='$cluster',topic='$topic'}[5m])) by (topic)"
    }
   ]
  },
  {
   "title": "consumer group lag with topic",
   "type": "graph",
   "description": "选中topic对应的所有的consumer group的堆积量，不区分单个partition，统计得是所有partition的lag之和",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_burrow_partition_lag{service='$instance',cluster='$cluster',topic='$topic'}) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "consumer group lag with partition",
   "type": "graph",
   "description": "topic和gourp都只能单选，结果为选中的topic的consumergroup在topic的每个partition上的数据堆积量",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_burrow_partition_lag{service='$instance',cluster='$cluster',topic='$topic',group='$group'}) by (partition)",
     "legendFormat": "$group-partition-{{partition}}"
    }
   ]
  },
  {
   "title": "Write records per seconds per partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_burrow_topic_partition_offset{service='$instance',cluster='$cluster',topic='$topic'}[5m])) by (partition)",
     "legendFormat": "partition-{{partition}}"
    }
   ]
  }
 ]
}