{
 "title": "Loki 2.0",
 "description": "Loki metrics via 2.0",
 "tags": [ "loki" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(log_messages_total)" }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "Messages Input",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(log_messages_total[1m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "S3 Request Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_s3_request_duration_seconds_bucket[5m])) by (le,operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Promtail Sent GB Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(promtail_sent_bytes_total)/1024/1024/1024",
     "legendFormat": "instance: {{ instance }}"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cassandra Request Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_cassandra_request_duration_seconds_bucket[5m])) by (le,operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Chunk Store Chunks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_chunk_store_chunks_per_query_bucket[5m])) by (le))",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Table-Manager Sync Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_table_manager_sync_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Received Lines / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Distributor  Received bytes / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "batch appends sent to ingesters / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "loki_distributor_ingester_append_failures_total",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Ingster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Blocks / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams)",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Streams Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total[5m])",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}