global:
  # -- if true, deploy with foundry unique configuration
  isViper: true
  # -- docker registry address
  dockerRegistry: "10.4.243.51:5000"
  # -- prometheus deploy namespace
  monitorNamespace: "monitoring"
  model:
    version:
      # -- viper face feature model version
      face: "25200"
      # -- viper pedestrian model version
      pedestrian: "15300"
      # -- viper automobile model version
      automobile: "11000"
      # -- viper carplate model version
      carplate: "10500"
      # -- viper human powered vehicle model version
      humanPoweredVehicle: "10100"
    configmap:
      # -- model configmap name
      name: "models-config"
      # -- model configmap namespace
      namespace: "default"


# -- kafka replica count
replicaCount: 3

# -- kafka name suffix
nameSuffix: "default"

# -- k8s nodeSelector
nodeSelector: {}
  # viper.sensetime.com/node-components: "True"

# -- k8s tolerations
tolerations: []

# -- k8s node/pod affinity/anti-affinity
affinity: {}

image:
  # -- image pull policy
  pullPolicy: "Always"
  # -- image pull secrets
  pullSecrets: ["inner"]
  repository:
    # -- kafka image repo
    kafka: "kafka"
    # -- busybox arm64 image repo
    busybox: "busybox"
  tag:
    # -- kafka multi arch image tag
    kafka: "3.6.1.debug4"
    # -- busybox multi arch image tag
    busybox: "1.33.0-amd64"

# -- pod security context
podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

service:
  kafka:
    # -- service type.
    type: "Headless"
    port:
      # -- kafka server port
      server: 9092
      # -- kafka server ssl port
      serverSSL: 9093
      # -- kafka metrics port
      metric: 7071
    # -- enable prometheus servicemonitor or not
    enableServiceMonitor: false

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.5"
    memory: "200Mi"

persistence:
  # -- mount how many pv for each replica
  pvcPerPod: 1
  # -- storageclass name
  storageClass: "local-kafka"
  # -- volume type, supported type is localvolume or emptydir
  volumeType: "localvolume" 
  # -- volume size, for example "100G"
  volumeSize: "1G"

property: 
  auth:
    # -- enable kafka auth or not
    enabled: true
  ssl: 
    # -- enable kafka ssl or not
    enabled: false
    # -- server certs secret name
    secretName: "infra-server-certs"
    # -- truststore password reference key
    truststorePasswdRef: "truststore_password"
    # -- keystore password reference key
    keystorePasswdRef: "keystore_password"
    # -- key password reference key
    keyPasswdRef: "key_password"
  # -- kafka network mode, hostNetwork or ClusterIP
  networkMode: "ClusterIP"
  # -- topic retention bytes, default is 10G
  retentionBytes: "10737418240"
  # -- topic retention hours, default is 1 week
  retentionHours: 168
  # -- java heap
  javaXmx: "16G"
  # -- auto create topics
  autoCreateTopics: false 

init:
  # -- init topics
  topics:
    - "oplog.tsfd.features.face_25300"
    - "oplog.tsfd.features.pedestrian_15500"

  # -- set init topic retention hours and bytes
  topicRetentions: []
  #  - topic_name: "mytopic"
  #    retention_hours: 8760          # 1 year
  #    retention_bytes: "10737418240"   # 10G
  topicPartitions: 32
