{{- if not .Values.global.isViper }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-secret
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  clickhouse_admin_username: {{ b64enc "admin" | quote }}
  clickhouse_admin_password: {{ randAlphaNum 8 | b64enc | quote }}
{{- end }}
