{{- $fullname := include "clickhouse.fullname" . -}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }} 
rules:
  - apiGroups: [""]
    resources:
      - endpoints
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }} 
subjects:
  - kind: ServiceAccount
    name: {{ $fullname }} 
