---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  {{- if eq "Headless" .Values.service.type }}
  clusterIP: None
  {{- end }}
  ports:
  - port: {{ .Values.service.port.rpc }}
    name: rpc
  - port: {{ .Values.service.port.rest }}
    name: rest
  - port: {{ .Values.service.port.internal }}
    name: interserver
  - port: {{ .Values.service.port.metrics }}
    name: metrics
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}

{{- range $i, $m := until (.Values.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" $ }}-{{ $i }}
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  {{- if eq "Headless" $.Values.service.type }}
  clusterIP: None
  {{- end }}
  ports:
  - port: {{ $.Values.service.port.rpc }}
    name: rpc
  - port: {{ $.Values.service.port.rest }}
    name: rest
  selector:
    {{- include "clickhouse.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "clickhouse.fullname" $ }}-{{ $i }}
{{- end }}
---
{{- if .Values.property.restPortExternalOpen }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" $ }}-nodeport
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - port: {{ .Values.service.port.rest }}
    name: rest
    nodePort: {{ .Values.service.port.restExternal }}
  selector:
    {{- include "clickhouse.selectorLabels" $ | nindent 4 }}
{{- end }}
