# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "create", "get", "list", "watch", "delete", "deletecollection" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create", "get", "list", "watch", "delete", "deletecollection" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-pod-creation-clusterwide
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-job-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
