apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-rest
  name: iot-rest
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30122
  selector:
    app: iot-rest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-rest
spec:
  selector:
    matchLabels:
      app: iot-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-rest
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: iot-rest
          image: "{{ .Values.image.repository }}/{{ .Values.image.rest.name }}:{{ .Values.image.rest.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config-volume
              mountPath: /.env
              subPath: env
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: config-volume
          configMap:
            name: iot-cfg

