apiVersion: v1
kind: Service
metadata:
  labels:
    app: mes-check
  name: mes-check
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30114
  selector:
    app: mes-check
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-check
spec:
  selector:
    matchLabels:
      app: mes-check
  replicas: 1
  template:
    metadata:
      labels:
        app: mes-check
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mes-check
          image: "{{ .Values.image.repository }}/{{ .Values.image.check.name }}:{{ .Values.image.check.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config-volume
              mountPath: /.env
              subPath: mes-env
            - name: config-volume
              mountPath: /config/method_target.json
              subPath: method_target.json
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: config-volume
          configMap:
            name: mes-cfg

