# Default values for clickhouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- If true, install with viper unique configuration
  isViper: true
  # -- machine architecture
  hostArch: "amd64"
  # -- docker registry address
  dockerRegistry: "10.4.243.51:5000"
  # -- prometheus deploy namespace
  monitorNamespace: "monitoring"

dep:
  zk:
    # -- zookeeper name suffix
    nameSuffix: "default"
    # -- zookeeper namespace
    namespace: "component"
    # -- zookeeper replicas
    replicas: 3
  kafka:
    # -- kafka name suffix
    nameSuffix: "default"
    # -- kafka namespace
    namespace: "component"
    # -- kafka replicas
    replicas: 3
    # -- kafka auth
    auth:
      enabled: true
      secretName: "kafka-default-secret"
      usernameRef: "kafka_admin_username"
      passwordRef: "kafka_admin_password"
  redis:
    # -- redis enabled
    enabled: true
    # -- redis name suffix
    nameSuffix: "olap"
    # -- redis namespace
    namespace: "component"
    # -- redis auth
    auth:
      enabled: true
      secretName: "redis-default-secret"
      usernameRef: "redis_admin_username"
      passwordRef: "redis_admin_password"

# -- name suffix
nameSuffix: "olap"

# -- clickhouse replicas
replicaCount: 3

# -- node selector
nodeSelector: {}

# -- tolerations
tolerations: []

# -- pod/node affinity/anti-affinity
affinity: {}

image:
  # -- image pull policy
  pullPolicy: "IfNotPresent"
  # -- image pull secrets
  pullSecrets: ["inner"]
  repository:
    amd64:
      # -- clickhouse amd64 image repo
      clickhouse: "clickhouse-server"
      # -- exporter amd64 image repo
      exporter: "clickhouse-exporter"
      # -- busybox amd64 image tag
      busybox: "busybox"
    arm64:
      # -- clickhouse arm64 image repo
      clickhouse: "infra/clickhouse/clickhouse-server"
      # -- exporter arm64 image repo
      exporter: "infra/f1yegor/clickhouse-exporter"
      # -- busybox arm64 image tag
      busybox: "viper-ce/library/busybox"
  tag:
    amd64:
      # -- clickhouse amd64 image tag
      clickhouse: "v22.1.3.7-stable-e3c1299"
      # -- exporter amd64 image tag
      exporter: "v1.1.1"
      # -- busybox amd64 image tag
      busybox: "1.33.0-amd64"
    arm64:
      # -- clickhouse arm64 image tag
      clickhouse: "v22.1.3.7-stable-e3c1299-arm64"
      # -- exporter arm64 image tag
      exporter: "v1.1.1-arm64"
      # -- busybox arm64 image tag
      busybox: "1.33.0-arm64"

# -- pod annotations
podAnnotations:
  pod.alpha.kubernetes.io/initialized: "true"

# -- pod security context
podSecurityContext: {}

# -- container security context
securityContext: {}

service:
  # -- service type
  type: "Headless"
  port:
    # -- rpc port
    rpc: 9000
    # -- rest port
    rest: 8123
    # -- rest external node port
    restExternal: 31181
    # -- internal server port
    internal: 9009
    # -- metrics port
    metrics: 9116
  # -- enable servicemonitor or not
  enableServiceMonitor: false

resources:
  # -- amd64 resources
  amd64:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "8"
      memory: "20Gi"
  # -- arm64 resources
  arm64:
    requests:
      cpu: "1.5"
      memory: "30Gi"
    limits:
      cpu: "1.5"
      memory: "30Gi"

persistence:
  # -- storageclass name
  storageClass: "local-clickhouse"
  # -- volume size requested
  volumeSize: "10G"

property:
  # -- kubernetes pods subnet
  kubePodsSubnet: ""
  # -- open external rest port
  restPortExternalOpen: false
  # -- max_memory_usage (Bytes), default 90GB
  maxMemoryUsage: "4000000000"

init:
  # -- init databases
  databases:
    - name: "bdp"
  username: "admin"
  password: "123456"
